# BC2406 Project

3 types:
* lin reg
* logistic reg
* CART (dec tree)

In [ ]:
%pip install pandas


In [21]:
import pandas as pd
import glob
import os
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import numpy as np
from sklearn.preprocessing import LabelEncoder

## Dataset 3

### Data Handling

In [ ]:

# rest of the code

#import csv files
# print(csv_files)
path=os.path.join(os.getcwd(),'data','3')
csv_files=glob.glob(path + "/*.csv")

#remove BC2406.ipynb from csv_files
# csv_files.remove('BC2406.ipynb')

# remove all files whose file name (not path) starts with SIMULATED
csv_files=[csv_file for csv_file in csv_files if not os.path.basename(csv_file).startswith('SIMULATED')]

dataframes={}

print(csv_files)
for csv_file in csv_files:
  # print(csv_file)
  well_name=os.path.splitext(csv_file)[0]
  # print("file path")
  # print(os.path.join(csv_directory,csv_file))
  df=pd.read_csv(csv_file)
  dataframes[well_name]=df

for well_name,df in dataframes.items():
  df.insert(0,'name',well_name.split('_')[0].split('/')[-1])
  df.insert(1,'id',well_name.split('_')[1])

df=pd.concat(dataframes.values(),ignore_index=True)

distinct_wells=df['name'].unique()
for name in distinct_wells:
  print(name)

df

In [ ]:
# show all values in column class
print(df['class'].unique())

#count number of 0, 3 in class label
print("count of 0 in class label: ",len(df[df['class']==0])) # normal state
print("count of 3 in class label: ",len(df[df['class']==3]))  # warning state

In [ ]:
df.dropna()
#clean dataset to remove name, id, timestamp
df=df.drop(['name','id','timestamp'],axis=1)

df=df.fillna(0)



In [ ]:
#split dataset into train and test
from sklearn.model_selection import train_test_split
X=df.drop(['class'],axis=1)
y=df['class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

### Generate Models

#### Logistic Regression

In [ ]:
# #train logistic regression model on training set against class label


# #train model on training set
# log_reg=LogisticRegression(max_iter=1000)
# log_reg.fit(X_train,y_train)

# #predict class label on training set
# logreg_train_set_predictions=log_reg.predict(X_train)

# #test model on test set
# logreg_test_set_predictions=log_reg.predict(X_test)
# log_accuracy=accuracy_score(y_test,logreg_test_set_predictions)
# log_confusion_matrix=confusion_matrix(y_test,logreg_test_set_predictions)
# log_classification_report=classification_report(y_test,logreg_test_set_predictions)




## Dataset 5 (Rapid Productivity Loss)

### Data Handling

In [65]:
import glob
import os
import pandas as pd

#import csv files
# print(csv_files)
path=os.path.join(os.getcwd(),'data','5')
csv_files=glob.glob(path + "/*.csv")

#remove BC2406.ipynb from csv_files
# csv_files.remove('BC2406.ipynb')

dataframes={}

print(csv_files)
for csv_file in csv_files:
  # print(csv_file)
  well_name=os.path.splitext(csv_file)[0]
  # print("file path")
  # print(os.path.join(csv_directory,csv_file))
  df=pd.read_csv(csv_file)
  dataframes[well_name]=df

for well_name,df in dataframes.items():
  df.insert(0,'name',well_name.split('_')[0])
  df.insert(1,'id',well_name.split('_')[1])

df=pd.concat(dataframes.values(),ignore_index=True)

distinct_wells=df['name'].unique()
for name in distinct_wells:
  print(name)

df





['/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00015_20171013140047.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00016_20180517222322.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00017_20140319141450.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00016_20180405020345.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00016_20180426142005.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00017_20140318160220.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00015_20170620160349.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00017_20140314180000.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-

/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00015
/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00016
/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00017


name              id  \
0       /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
1       /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
2       /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
3       /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
4       /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
...                                                   ...             ...   
361993  /Users/dyllon/Library/Mobile Documents/com~app...  20180426145108   
361994  /Users/dyllon/Library/Mobile Documents/com~app...  20180426145108   
361995  /Users/dyllon/Library/Mobile Documents/com~app...  20180426145108   
361996  /Users/dyllon/Library/Mobile Documents/com~app...  20180426145108   
361997  /Users/dyllon/Library/Mobile Documents/com~app...  20180426145108   

                         timestamp       P-PDG       P-TPT     T-TPT  \
0       2017-10-13 14:00:47.000000  23639730.0         0.0   0.00000   
1       2017-10-13 14:00:48.000000  23640270.0         0.0   0.00000   
2       2017-10-13 14:00:49.000000  23640810.0         0.0   0.00000   
3       2017-10-13 14:00:50.000000  23641350.0         0.0   0.00000   
4       2017-10-13 14:00:51.000000  23641890.0         0.0   0.00000   
...                            ...         ...         ...       ...   
361993  2018-04-26 15:44:16.000000  24660500.0  11091050.0  16.99739   
361994  2018-04-26 15:44:17.000000  24660460.0  11091230.0  16.99959   
361995  2018-04-26 15:44:18.000000  24660420.0  11091420.0  17.00179   
361996  2018-04-26 15:44:19.000000  24660380.0  11091610.0  17.00399   
361997  2018-04-26 15:44:20.000000  24660340.0  11091800.0  17.00619   

        P-MON-CKP  T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL       QGL  class  
0       3509006.0   42.35576  19960610.0         NaN  1.288151    0.0  
1       3483324.0   42.35957  19978070.0         NaN  1.291373    0.0  
2       3449990.0   42.36337  19995540.0         NaN  1.294595    0.0  
3       3416657.0   42.36717  20013010.0         NaN  1.297816    0.0  
4       3383324.0   42.37098  20030480.0         NaN  1.302506    0.0  
...           ...        ...         ...         ...       ...    ...  
361993   845799.3   50.32685  18913280.0         NaN  1.766007    5.0  
361994   845819.6   50.32632  18913740.0         NaN  1.736611    5.0  
361995   845840.0   50.32579  18914190.0         NaN  1.707214    5.0  
361996   845860.3   50.32526  18914650.0         NaN  1.677818    5.0  
361997   845880.7   50.32472  18915110.0         NaN  1.648421    5.0  

[361998 rows x 12 columns]

In [66]:
df.head()

name              id  \
0  /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
1  /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
2  /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
3  /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
4  /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   

                    timestamp       P-PDG  P-TPT  T-TPT  P-MON-CKP  T-JUS-CKP  \
0  2017-10-13 14:00:47.000000  23639730.0    0.0    0.0  3509006.0   42.35576   
1  2017-10-13 14:00:48.000000  23640270.0    0.0    0.0  3483324.0   42.35957   
2  2017-10-13 14:00:49.000000  23640810.0    0.0    0.0  3449990.0   42.36337   
3  2017-10-13 14:00:50.000000  23641350.0    0.0    0.0  3416657.0   42.36717   
4  2017-10-13 14:00:51.000000  23641890.0    0.0    0.0  3383324.0   42.37098   

   P-JUS-CKGL  T-JUS-CKGL       QGL  class  
0  19960610.0         NaN  1.288151    0.0  
1  19978070.0         NaN  1.291373    0.0  
2  19995540.0         NaN  1.294595    0.0  
3  20013010.0         NaN  1.297816    0.0  
4  20030480.0         NaN  1.302506    0.0

In [67]:
df.dropna()
#clean dataset to remove name, id, timestamp
df=df.drop(['name','id','timestamp'],axis=1)

#replace all NaN with 0
df=df.fillna(0)


In [68]:
#count number of 0, 5 and 105 in class label
print("count of 0 in class label",len(df[df['class']==0])) # normal state
print("count of 5 in class label",len(df[df['class']==5]))  # warning state
print("count of 105 in class label",len(df[df['class']==105])) # abnormal state


count of 0 in class label 33693
count of 5 in class label 10147
count of 105 in class label 318158


In [69]:
#split dataset into train and test
from sklearn.model_selection import train_test_split
X=df.drop(['class'],axis=1)
y=df['class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

### Generate Models

#### Logistic Regression

In [70]:
#train logistic regression model on training set against class label
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

#train model on training set
log_reg=LogisticRegression(max_iter=1000)
log_reg.fit(X_train,y_train)

#predict class label on training set
logreg_train_set_predictions=log_reg.predict(X_train)

#test model on test set
logreg_test_set_predictions=log_reg.predict(X_test)
log_accuracy=accuracy_score(y_test,logreg_test_set_predictions)
log_confusion_matrix=confusion_matrix(y_test,logreg_test_set_predictions)
log_classification_report=classification_report(y_test,logreg_test_set_predictions)




In [71]:
print("log_accuracy\n",log_accuracy)
print(log_confusion_matrix)
print(log_classification_report)
print("log_accuracy = %.1f"%(log_accuracy*100),"%")


log_accuracy
 0.8598066298342542
[[  402   415  5987]
 [    0   659  1324]
 [  867  1557 61189]]
              precision    recall  f1-score   support

         0.0       0.32      0.06      0.10      6804
         5.0       0.25      0.33      0.29      1983
       105.0       0.89      0.96      0.93     63613

    accuracy                           0.86     72400
   macro avg       0.49      0.45      0.44     72400
weighted avg       0.82      0.86      0.83     72400

log_accuracy = 86.0 %


#### Decision Tree

In [72]:
#train decision tree regression model on training set against class label
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

#train model on training set
dt_reg=DecisionTreeRegressor()
dt_reg.fit(X_train,y_train)

#predict class label on training set
dectree_train_set_predictions=dt_reg.predict(X_train)

#test model on test set
dectree_test_set_predictions=dt_reg.predict(X_test)
dt_mse=mean_squared_error(y_test,dectree_test_set_predictions)
dt_rmse=np.sqrt(dt_mse)
dt_accuracy=accuracy_score(y_test,dectree_test_set_predictions)
dt_confusion_matrix=confusion_matrix(y_test,dectree_test_set_predictions)



In [73]:
print("dt_mse\n",dt_mse)
print("dt_rmse\n",dt_rmse)
print("dt_accuracy\n",dt_accuracy)
print(dt_confusion_matrix)
print("dt_accuracy = %.1f"%(dt_accuracy*100),"%")


dt_mse
 0.7624309392265194
dt_rmse
 0.8731729148493552
dt_accuracy
 0.9998895027624309
[[ 6799     2     3]
 [    1  1982     0]
 [    2     0 63611]]
dt_accuracy = 100.0 %


In [74]:
%pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [75]:
import xgboost as xgb



In [76]:
le = LabelEncoder()
y_trainLE = le.fit_transform(y_train)

In [77]:
xgb_reg=xgb.XGBRegressor()
xgb_reg.fit(X_train,y_trainLE)

#predict class label on training set
xgb_train_set_predictions=xgb_reg.predict(X_train)

#test model on test set
y_pred=xgb_reg.predict(X_test)



/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/xgboost/data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/xgboost/data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/xgboost/data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.

In [78]:
#train logistic regression model on training set against class label
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

#convert y_pred to 0,5,105
y_pred=np.round(y_pred)
y_pred=le.inverse_transform(y_pred.astype(int))

xgb_accuracy=accuracy_score(y_test,y_pred)
xgb_confusion_matrix=confusion_matrix(y_test,y_pred)
xgb_classification_report=classification_report(y_test,y_pred)

print("xgb_accuracy\n",xgb_accuracy)
print(xgb_confusion_matrix)
print(xgb_classification_report)


xgb_accuracy
 0.9994889502762431
[[ 6791    13     0]
 [    0  1983     0]
 [    5    19 63589]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      6804
         5.0       0.98      1.00      0.99      1983
       105.0       1.00      1.00      1.00     63613

    accuracy                           1.00     72400
   macro avg       0.99      1.00      1.00     72400
weighted avg       1.00      1.00      1.00     72400



In [79]:
# %pip install --no-build-isolation catboost

CatBoost

In [80]:
from catboost import CatBoostRegressor


ModuleNotFoundError: No module named 'catboost'

In [ ]:
le = LabelEncoder()
y_trainLE = le.fit_transform(y_train)

In [ ]:


cat_reg=CatBoostRegressor()
cat_reg.fit(X_train,y_trainLE)

#predict class label on training set
cat_train_set_predictions=cat_reg.predict(X_train)

#test model on test set
cat_test_set_predictions=cat_reg.predict(X_test)


In [ ]:
#convert y_pred to 0,5,105
cat_test_set_predictions=np.round(cat_test_set_predictions)
cat_test_set_predictions=le.inverse_transform(cat_test_set_predictions.astype(int))

cat_accuracy=accuracy_score(y_test,cat_test_set_predictions)
cat_confusion_matrix=confusion_matrix(y_test,cat_test_set_predictions)

print("cat_accuracy\n",cat_accuracy)
print(cat_confusion_matrix)
print(xgb_classification_report)

LightGBM

In [ ]:
%pip install --upgrade lightgbm

  Obtaining dependency information for lightgbm from https://files.pythonhosted.org/packages/56/f3/6f77fe5fa45722582e52efc2833288fa670abfbec57eea433e83820f5b90/lightgbm-4.1.0-py3-none-macosx_10_15_x86_64.macosx_11_6_x86_64.macosx_12_5_x86_64.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 9.5 MB/s eta 0:00:00:00:0100:01
Note: you may need to restart the kernel to use updated packages.


In [ ]:
import lightgbm as lgb


In [ ]:
#train lightgbm regression model on training set against class label


lgb_reg=lgb.LGBMClassifier()
lgb_reg.fit(X_train,y_train)

#predict class label on training set
lgb_train_set_predictions=lgb_reg.predict(X_train)

#test model on test set
lgb_test_set_predictions=lgb_reg.predict(X_test)





[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004288 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1785
[LightGBM] [Info] Number of data points in the train set: 289598, number of used features: 7
[LightGBM] [Info] Start training from score -2.376776
[LightGBM] [Info] Start training from score -3.568760
[LightGBM] [Info] Start training from score -0.129016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


In [ ]:

lgb_accuracy=accuracy_score(y_test,lgb_test_set_predictions)
lgb_confusion_matrix=confusion_matrix(y_test,lgb_test_set_predictions)
lgb_classification_report=classification_report(y_test,lgb_test_set_predictions)

print("lgb_accuracy\n",lgb_accuracy)
print(lgb_confusion_matrix)
print(xgb_classification_report)

lgb_accuracy
 0.9996823204419889
[[ 6790     7     7]
 [    1  1982     0]
 [    8     0 63605]]


NameError: name 'xgb_classification_report' is not defined

### Compare Models

In [ ]:
# compare both models with f1 score
from sklearn.metrics import f1_score

# calculate F1 scores for both models
logreg_f1 = f1_score(y_test, logreg_test_set_predictions, average='weighted')
dectree_f1 = f1_score(y_test, dectree_test_set_predictions, average='weighted')

# print
print("F1 scores:")
print("Logistic Regression: ", logreg_f1)
print("Decision Tree Regressor: ", dectree_f1)

# compare F1 scores
if logreg_f1 > dectree_f1:
    print("Logistic Regression has a higher F1 score.")
elif logreg_f1 < dectree_f1:
    print("Decision Tree has a higher F1 score.")
else:
    print("Both models have the same F1 score.")




## Dataset 7

### Data Handling

In [ ]:
import glob
import os
import pandas as pd

#import csv files
# print(csv_files)
path=os.path.join(os.getcwd(),'data','7')
csv_files=glob.glob(path + "/*.csv")

#remove BC2406.ipynb from csv_files
# csv_files.remove('BC2406.ipynb')

# remove all files whose file name (not path) starts with SIMULATED
csv_files=[csv_file for csv_file in csv_files if not os.path.basename(csv_file).startswith('DRAWN')]

dataframes={}

print(csv_files)
for csv_file in csv_files:
  # print(csv_file)
  well_name=os.path.splitext(csv_file)[0]
  # print("file path")
  # print(os.path.join(csv_directory,csv_file))
  df=pd.read_csv(csv_file)
  dataframes[well_name]=df

for well_name,df in dataframes.items():
  df.insert(0,'name',well_name.split('_')[0].split('/')[-1])
  df.insert(1,'id',well_name.split('_')[1])

df=pd.concat(dataframes.values(),ignore_index=True)

distinct_wells=df['name'].unique()
for name in distinct_wells:
  print(name)

df

['/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/7/WELL-00006_20180620181348.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/7/WELL-00006_20180618110721.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/7/WELL-00001_20170226220309.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/7/WELL-00018_20180611040207.csv']
WELL-00006
WELL-00001
WELL-00018


name              id                   timestamp         P-PDG  \
0       WELL-00006  20180620181348  2018-06-20 18:13:48.000000 -1.180116e+42   
1       WELL-00006  20180620181348  2018-06-20 18:13:49.000000 -1.180116e+42   
2       WELL-00006  20180620181348  2018-06-20 18:13:50.000000 -1.180116e+42   
3       WELL-00006  20180620181348  2018-06-20 18:13:51.000000 -1.180116e+42   
4       WELL-00006  20180620181348  2018-06-20 18:13:52.000000 -1.180116e+42   
...            ...             ...                         ...           ...   
271703  WELL-00018  20180611040207  2018-06-11 12:58:09.000000  0.000000e+00   
271704  WELL-00018  20180611040207  2018-06-11 12:58:10.000000  0.000000e+00   
271705  WELL-00018  20180611040207  2018-06-11 12:58:11.000000  0.000000e+00   
271706  WELL-00018  20180611040207  2018-06-11 12:58:12.000000  0.000000e+00   
271707  WELL-00018  20180611040207  2018-06-11 12:58:13.000000  0.000000e+00   

             P-TPT     T-TPT   P-MON-CKP  T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  \
0       21125440.0  117.6264  12038980.0   65.97606   1627220.0         NaN   
1       21125550.0  117.6270  12039360.0   65.97627   1627243.0         NaN   
2       21125650.0  117.6277  12039750.0   65.97648   1627266.0         NaN   
3       21125760.0  117.6283  12040130.0   65.97669   1627290.0         NaN   
4       21125860.0  117.6290  12040520.0   65.97691   1627313.0         NaN   
...            ...       ...         ...        ...         ...         ...   
271703   8721603.0  109.4972   2195037.0   68.44791   8454861.0         NaN   
271704   8721549.0  109.4979   2195037.0   68.44791   8454861.0         NaN   
271705   8721495.0  109.4987   2195037.0   68.44791   8454861.0         NaN   
271706   8721441.0  109.4994   2195037.0   68.44791   8454861.0         NaN   
271707   8721387.0  109.5001   2195037.0   68.44791   8454861.0         NaN   

        QGL  class  
0       0.0    0.0  
1       0.0    0.0  
2       0.0    0.0  
3       0.0    0.0  
4       0.0    0.0  
...     ...    ...  
271703  0.0  107.0  
271704  0.0  107.0  
271705  0.0  107.0  
271706  0.0  107.0  
271707  0.0  107.0  

[271708 rows x 12 columns]

In [ ]:
df.dropna()
#clean dataset to remove name, id, timestamp
df=df.drop(['name','id','timestamp', 'T-JUS-CKGL'],axis=1)

#replace all NaN with 0
# df=df.fillna(0)

# drop all rows with class NaN
df=df.dropna(subset=['class'])

# print NaN in any column

# drop all rows where P-PDG is NaN
df=df.dropna(subset=['P-PDG'])

print(df[df.isna().any(axis=1)])



Empty DataFrame
Columns: [P-PDG, P-TPT, T-TPT, P-MON-CKP, T-JUS-CKP, P-JUS-CKGL, QGL, class]
Index: []


In [ ]:
# show all values in column class
print(df['class'].unique())

# print 5 rows where class = NaN
print(df[df['class'].isna()].head())

#count number of 0, 3 in class label
print("count of 0 in class label: ",len(df[df['class']==0])) # normal state
print("count of NaN in class label: ",len(df[df['class'].isna()])) # normal state
print("count of 7 in class label: ",len(df[df['class']==7]))  # warning state
print("count of 107 in class label: ",len(df[df['class']==107]))  # error state


[  0. 107.   7.]
Empty DataFrame
Columns: [P-PDG, P-TPT, T-TPT, P-MON-CKP, T-JUS-CKP, P-JUS-CKGL, QGL, class]
Index: []
count of 0 in class label:  12526
count of NaN in class label:  0
count of 7 in class label:  821
count of 107 in class label:  257366


In [ ]:
#split dataset into train and test
from sklearn.model_selection import train_test_split
X=df.drop(['class'],axis=1)
y=df['class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

### Generate Models

#### Logistic Regression

In [ ]:
#train logistic regression model on training set against class label
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler

# scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#train model on training set
log_reg=LogisticRegression(max_iter=100000)
log_reg.fit(X_train_scaled,y_train)

#predict class label on training set
logreg_train_set_predictions=log_reg.predict(X_train_scaled)

#test model on test set
logreg_test_set_predictions=log_reg.predict(X_test_scaled)
log_accuracy=accuracy_score(y_test,logreg_test_set_predictions)
log_confusion_matrix=confusion_matrix(y_test,logreg_test_set_predictions)
log_classification_report=classification_report(y_test,logreg_test_set_predictions)


In [ ]:
print("log_accuracy\n",log_accuracy)
print(log_confusion_matrix)
print(log_classification_report)
print("log_accuracy = %.1f"%(log_accuracy*100),"%")

#### Decision Tree

In [ ]:
#train decision tree regression model on training set against class label
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

X_train = np.nan_to_num(X_train.astype(np.float64))
X_test = np.nan_to_num(X_test.astype(np.float64))

# check for infinite or NaN values in X_train and X_test
if not np.isfinite(X_train).all() or not np.isfinite(X_test).all():
    print("Input data contains infinite or NaN values.")

#train model on training set
dt_reg=DecisionTreeRegressor()
dt_reg.fit(X_train,y_train)

#predict class label on training set
dectree_train_set_predictions=dt_reg.predict(X_train)

#test model on test set
dectree_test_set_predictions=dt_reg.predict(X_test)
dt_mse=mean_squared_error(y_test,dectree_test_set_predictions)
dt_rmse=np.sqrt(dt_mse)
dt_accuracy=accuracy_score(y_test,dectree_test_set_predictions)
dt_confusion_matrix=confusion_matrix(y_test,dectree_test_set_predictions)


In [ ]:
print("dt_mse\n",dt_mse)
print("dt_rmse\n",dt_rmse)
print("dt_accuracy\n",dt_accuracy)
print(dt_confusion_matrix)
print("dt_accuracy = %.1f"%(dt_accuracy*100),"%")


In [ ]:
import xgboost as xgb

In [ ]:
le = LabelEncoder()
y_trainLE = le.fit_transform(y_train)
xgb_reg=xgb.XGBRegressor()
xgb_reg.fit(X_train,y_trainLE) # this gives me error help

#predict class label on training set
xgb_train_set_predictions=xgb_reg.predict(X_train)

#test model on test set
y_pred=xgb_reg.predict(X_test)


In [ ]:
#train logistic regression model on training set against class label
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

#convert y_pred to 0,5,105
y_pred=np.round(y_pred)
y_pred=le.inverse_transform(y_pred.astype(int))

xgb_accuracy=accuracy_score(y_test,y_pred)
xgb_confusion_matrix=confusion_matrix(y_test,y_pred)
xgb_classification_report=classification_report(y_test,y_pred)

print("xgb_accuracy\n",xgb_accuracy)
print(xgb_confusion_matrix)
print(xgb_classification_report)

NameError: name 'y_pred' is not defined

## Review

In [ ]:
print()