# BC2406 Project

3 types:
* lin reg
* logistic reg
* CART (dec tree)

## Dataset 3

### Data Handling

In [6]:
import glob
import os
import pandas as pd

#import csv files
# print(csv_files)
path=os.path.join(os.getcwd(),'data','3')
csv_files=glob.glob(path + "/*.csv")

#remove BC2406.ipynb from csv_files
# csv_files.remove('BC2406.ipynb')

# remove all files whose file name (not path) starts with SIMULATED
csv_files=[csv_file for csv_file in csv_files if not os.path.basename(csv_file).startswith('SIMULATED')]

dataframes={}

print(csv_files)
for csv_file in csv_files:
  # print(csv_file)
  well_name=os.path.splitext(csv_file)[0]
  # print("file path")
  # print(os.path.join(csv_directory,csv_file))
  df=pd.read_csv(csv_file)
  dataframes[well_name]=df

for well_name,df in dataframes.items():
  df.insert(0,'name',well_name.split('_')[0].split('/')[-1])
  df.insert(1,'id',well_name.split('_')[1])

df=pd.concat(dataframes.values(),ignore_index=True)

distinct_wells=df['name'].unique()
for name in distinct_wells:
  print(name)

df

['/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-00014_20170921200114.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-00014_20170925160218.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-00014_20170926170228.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-00014_20170920010042.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-00014_20170920060228.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-00014_20170921050404.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-00014_20170921100155.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-00001_20170320130025.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-

WELL-00014
WELL-00001


name              id                   timestamp       P-PDG  \
0       WELL-00014  20170921200114  2017-09-21 20:01:14.000000  24389400.0   
1       WELL-00014  20170921200114  2017-09-21 20:01:15.000000  24388900.0   
2       WELL-00014  20170921200114  2017-09-21 20:01:16.000000  24388410.0   
3       WELL-00014  20170921200114  2017-09-21 20:01:17.000000  24388120.0   
4       WELL-00014  20170921200114  2017-09-21 20:01:18.000000  24387820.0   
...            ...             ...                         ...         ...   
569147  WELL-00014  20170917150000  2017-09-17 19:56:11.000000  23525310.0   
569148  WELL-00014  20170917150000  2017-09-17 19:56:12.000000  23525260.0   
569149  WELL-00014  20170917150000  2017-09-17 19:56:13.000000  23525200.0   
569150  WELL-00014  20170917150000  2017-09-17 19:56:14.000000  23525150.0   
569151  WELL-00014  20170917150000  2017-09-17 19:56:15.000000  23525100.0   

             P-TPT     T-TPT  P-MON-CKP  T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  \
0       15923800.0  43.65952  1490977.0   31.00947  19415620.0         NaN   
1       15923280.0  43.65860  1492114.0   31.00781  19415860.0         NaN   
2       15922750.0  43.65767  1493250.0   31.00614  19416100.0         NaN   
3       15921120.0  43.65464  1494386.0   31.00448  19416350.0         NaN   
4       15919480.0  43.65160  1495523.0   31.00282  19416590.0         NaN   
...            ...       ...        ...        ...         ...         ...   
569147  13954990.0  56.54493  1893704.0   38.29067  19560470.0         NaN   
569148  13955230.0  56.54481  1894765.0   38.29134  19561440.0         NaN   
569149  13955470.0  56.54469  1895825.0   38.29200  19562410.0         NaN   
569150  13955710.0  56.54458  1896431.0   38.29267  19563380.0         NaN   
569151  13955950.0  56.54446  1897037.0   38.29333  19564350.0         NaN   

             QGL  class  
0       1.243595      3  
1       1.239152      3  
2       1.234708      3  
3       1.230265      3  
4       1.225821      3  
...          ...    ...  
569147  1.265560      3  
569148  1.278255      3  
569149  1.290949      3  
569150  1.303643      3  
569151  1.316338      3  

[569152 rows x 12 columns]

In [7]:
# show all values in column class
print(df['class'].unique())

#count number of 0, 3 in class label
print("count of 0 in class label: ",len(df[df['class']==0])) # normal state
print("count of 3 in class label: ",len(df[df['class']==3]))  # warning state

[3]
count of 0 in class label:  0
count of 3 in class label:  569152


In [8]:
df.dropna()
#clean dataset to remove name, id, timestamp
df=df.drop(['name','id','timestamp'],axis=1)

df=df.fillna(0)



In [9]:
#split dataset into train and test
from sklearn.model_selection import train_test_split
X=df.drop(['class'],axis=1)
y=df['class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

### Generate Models

#### Logistic Regression

In [10]:
#train logistic regression model on training set against class label
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

#train model on training set
log_reg=LogisticRegression(max_iter=1000)
log_reg.fit(X_train,y_train)

#predict class label on training set
logreg_train_set_predictions=log_reg.predict(X_train)

#test model on test set
logreg_test_set_predictions=log_reg.predict(X_test)
log_accuracy=accuracy_score(y_test,logreg_test_set_predictions)
log_confusion_matrix=confusion_matrix(y_test,logreg_test_set_predictions)
log_classification_report=classification_report(y_test,logreg_test_set_predictions)




ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 3

## Dataset 5 (Rapid Productivity Loss)

### Data Handling

In [12]:
import glob
import os
import pandas as pd

#import csv files
# print(csv_files)
path=os.path.join(os.getcwd(),'data','5')
csv_files=glob.glob(path + "/*.csv")

#remove BC2406.ipynb from csv_files
# csv_files.remove('BC2406.ipynb')

dataframes={}

print(csv_files)
for csv_file in csv_files:
  # print(csv_file)
  well_name=os.path.splitext(csv_file)[0]
  # print("file path")
  # print(os.path.join(csv_directory,csv_file))
  df=pd.read_csv(csv_file)
  dataframes[well_name]=df

for well_name,df in dataframes.items():
  df.insert(0,'name',well_name.split('_')[0])
  df.insert(1,'id',well_name.split('_')[1])

df=pd.concat(dataframes.values(),ignore_index=True)

distinct_wells=df['name'].unique()
for name in distinct_wells:
  print(name)

df





['/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00015_20171013140047.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00016_20180517222322.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00017_20140319141450.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00016_20180405020345.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00016_20180426142005.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00017_20140318160220.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00015_20170620160349.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00017_20140314180000.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-

name              id  \
0       /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
1       /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
2       /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
3       /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
4       /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
...                                                   ...             ...   
361993  /Users/dyllon/Library/Mobile Documents/com~app...  20180426145108   
361994  /Users/dyllon/Library/Mobile Documents/com~app...  20180426145108   
361995  /Users/dyllon/Library/Mobile Documents/com~app...  20180426145108   
361996  /Users/dyllon/Library/Mobile Documents/com~app...  20180426145108   
361997  /Users/dyllon/Library/Mobile Documents/com~app...  20180426145108   

                         timestamp       P-PDG       P-TPT     T-TPT  \
0       2017-10-13 14:00:47.000000  23639730.0         0.0   0.00000   
1       2017-10-13 14:00:48.000000  23640270.0         0.0   0.00000   
2       2017-10-13 14:00:49.000000  23640810.0         0.0   0.00000   
3       2017-10-13 14:00:50.000000  23641350.0         0.0   0.00000   
4       2017-10-13 14:00:51.000000  23641890.0         0.0   0.00000   
...                            ...         ...         ...       ...   
361993  2018-04-26 15:44:16.000000  24660500.0  11091050.0  16.99739   
361994  2018-04-26 15:44:17.000000  24660460.0  11091230.0  16.99959   
361995  2018-04-26 15:44:18.000000  24660420.0  11091420.0  17.00179   
361996  2018-04-26 15:44:19.000000  24660380.0  11091610.0  17.00399   
361997  2018-04-26 15:44:20.000000  24660340.0  11091800.0  17.00619   

        P-MON-CKP  T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL       QGL  class  
0       3509006.0   42.35576  19960610.0         NaN  1.288151    0.0  
1       3483324.0   42.35957  19978070.0         NaN  1.291373    0.0  
2       3449990.0   42.36337  19995540.0         NaN  1.294595    0.0  
3       3416657.0   42.36717  20013010.0         NaN  1.297816    0.0  
4       3383324.0   42.37098  20030480.0         NaN  1.302506    0.0  
...           ...        ...         ...         ...       ...    ...  
361993   845799.3   50.32685  18913280.0         NaN  1.766007    5.0  
361994   845819.6   50.32632  18913740.0         NaN  1.736611    5.0  
361995   845840.0   50.32579  18914190.0         NaN  1.707214    5.0  
361996   845860.3   50.32526  18914650.0         NaN  1.677818    5.0  
361997   845880.7   50.32472  18915110.0         NaN  1.648421    5.0  

[361998 rows x 12 columns]

In [13]:
df.head()

name              id  \
0  /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
1  /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
2  /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
3  /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
4  /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   

                    timestamp       P-PDG  P-TPT  T-TPT  P-MON-CKP  T-JUS-CKP  \
0  2017-10-13 14:00:47.000000  23639730.0    0.0    0.0  3509006.0   42.35576   
1  2017-10-13 14:00:48.000000  23640270.0    0.0    0.0  3483324.0   42.35957   
2  2017-10-13 14:00:49.000000  23640810.0    0.0    0.0  3449990.0   42.36337   
3  2017-10-13 14:00:50.000000  23641350.0    0.0    0.0  3416657.0   42.36717   
4  2017-10-13 14:00:51.000000  23641890.0    0.0    0.0  3383324.0   42.37098   

   P-JUS-CKGL  T-JUS-CKGL       QGL  class  
0  19960610.0         NaN  1.288151    0.0  
1  19978070.0         NaN  1.291373    0.0  
2  19995540.0         NaN  1.294595    0.0  
3  20013010.0         NaN  1.297816    0.0  
4  20030480.0         NaN  1.302506    0.0

In [14]:
df.dropna()
#clean dataset to remove name, id, timestamp
df=df.drop(['name','id','timestamp'],axis=1)

#replace all NaN with 0
df=df.fillna(0)


In [15]:
#count number of 0, 5 and 105 in class label
print("count of 0 in class label",len(df[df['class']==0])) # normal state
print("count of 5 in class label",len(df[df['class']==5]))  # warning state
print("count of 105 in class label",len(df[df['class']==105])) # abnormal state


count of 0 in class label 33693
count of 5 in class label 10147
count of 105 in class label 318158


In [16]:
#split dataset into train and test
from sklearn.model_selection import train_test_split
X=df.drop(['class'],axis=1)
y=df['class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

### Generate Models

#### Logistic Regression

In [17]:
#train logistic regression model on training set against class label
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

#train model on training set
log_reg=LogisticRegression(max_iter=1000)
log_reg.fit(X_train,y_train)

#predict class label on training set
logreg_train_set_predictions=log_reg.predict(X_train)

#test model on test set
logreg_test_set_predictions=log_reg.predict(X_test)
log_accuracy=accuracy_score(y_test,logreg_test_set_predictions)
log_confusion_matrix=confusion_matrix(y_test,logreg_test_set_predictions)
log_classification_report=classification_report(y_test,logreg_test_set_predictions)




In [18]:
print("log_accuracy\n",log_accuracy)
print(log_confusion_matrix)
print(log_classification_report)
print("log_accuracy = %.1f"%(log_accuracy*100),"%")


log_accuracy
 0.8598066298342542
[[  402   415  5987]
 [    0   659  1324]
 [  867  1557 61189]]
              precision    recall  f1-score   support

         0.0       0.32      0.06      0.10      6804
         5.0       0.25      0.33      0.29      1983
       105.0       0.89      0.96      0.93     63613

    accuracy                           0.86     72400
   macro avg       0.49      0.45      0.44     72400
weighted avg       0.82      0.86      0.83     72400

log_accuracy = 86.0 %


#### Decision Tree

In [20]:
#train decision tree regression model on training set against class label
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

#train model on training set
dt_reg=DecisionTreeRegressor()
dt_reg.fit(X_train,y_train)

#predict class label on training set
dectree_train_set_predictions=dt_reg.predict(X_train)

#test model on test set
dectree_test_set_predictions=dt_reg.predict(X_test)
dt_mse=mean_squared_error(y_test,dectree_test_set_predictions)
dt_rmse=np.sqrt(dt_mse)
dt_accuracy=accuracy_score(y_test,dectree_test_set_predictions)
dt_confusion_matrix=confusion_matrix(y_test,dectree_test_set_predictions)



In [21]:
print("dt_mse\n",dt_mse)
print("dt_rmse\n",dt_rmse)
print("dt_accuracy\n",dt_accuracy)
print(dt_confusion_matrix)
print("dt_accuracy = %.1f"%(dt_accuracy*100),"%")


dt_mse
 0.9147099447513812
dt_rmse
 0.9564046971608731
dt_accuracy
 0.9998756906077348
[[ 6799     2     3]
 [    1  1982     0]
 [    3     0 63610]]
dt_accuracy = 100.0 %


### Compare Models

In [22]:
# compare both models with f1 score
from sklearn.metrics import f1_score

# calculate F1 scores for both models
logreg_f1 = f1_score(y_test, logreg_test_set_predictions, average='weighted')
dectree_f1 = f1_score(y_test, dectree_test_set_predictions, average='weighted')

# print
print("F1 scores:")
print("Logistic Regression: ", logreg_f1)
print("Decision Tree Regressor: ", dectree_f1)

# compare F1 scores
if logreg_f1 > dectree_f1:
    print("Logistic Regression has a higher F1 score.")
elif logreg_f1 < dectree_f1:
    print("Decision Tree has a higher F1 score.")
else:
    print("Both models have the same F1 score.")




F1 scores:
Logistic Regression:  0.8310721181154889
Decision Tree Regressor:  0.9998756912625324
Decision Tree has a higher F1 score.


## Dataset 7

### Data Handling

In [23]:
import glob
import os
import pandas as pd

#import csv files
# print(csv_files)
path=os.path.join(os.getcwd(),'data','7')
csv_files=glob.glob(path + "/*.csv")

#remove BC2406.ipynb from csv_files
# csv_files.remove('BC2406.ipynb')

# remove all files whose file name (not path) starts with SIMULATED
csv_files=[csv_file for csv_file in csv_files if not os.path.basename(csv_file).startswith('DRAWN')]

dataframes={}

print(csv_files)
for csv_file in csv_files:
  # print(csv_file)
  well_name=os.path.splitext(csv_file)[0]
  # print("file path")
  # print(os.path.join(csv_directory,csv_file))
  df=pd.read_csv(csv_file)
  dataframes[well_name]=df

for well_name,df in dataframes.items():
  df.insert(0,'name',well_name.split('_')[0].split('/')[-1])
  df.insert(1,'id',well_name.split('_')[1])

df=pd.concat(dataframes.values(),ignore_index=True)

distinct_wells=df['name'].unique()
for name in distinct_wells:
  print(name)

df

['/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/7/WELL-00006_20180620181348.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/7/WELL-00006_20180618110721.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/7/WELL-00001_20170226220309.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/7/WELL-00018_20180611040207.csv']
WELL-00006
WELL-00001
WELL-00018


name              id                   timestamp         P-PDG  \
0       WELL-00006  20180620181348  2018-06-20 18:13:48.000000 -1.180116e+42   
1       WELL-00006  20180620181348  2018-06-20 18:13:49.000000 -1.180116e+42   
2       WELL-00006  20180620181348  2018-06-20 18:13:50.000000 -1.180116e+42   
3       WELL-00006  20180620181348  2018-06-20 18:13:51.000000 -1.180116e+42   
4       WELL-00006  20180620181348  2018-06-20 18:13:52.000000 -1.180116e+42   
...            ...             ...                         ...           ...   
271703  WELL-00018  20180611040207  2018-06-11 12:58:09.000000  0.000000e+00   
271704  WELL-00018  20180611040207  2018-06-11 12:58:10.000000  0.000000e+00   
271705  WELL-00018  20180611040207  2018-06-11 12:58:11.000000  0.000000e+00   
271706  WELL-00018  20180611040207  2018-06-11 12:58:12.000000  0.000000e+00   
271707  WELL-00018  20180611040207  2018-06-11 12:58:13.000000  0.000000e+00   

             P-TPT     T-TPT   P-MON-CKP  T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  \
0       21125440.0  117.6264  12038980.0   65.97606   1627220.0         NaN   
1       21125550.0  117.6270  12039360.0   65.97627   1627243.0         NaN   
2       21125650.0  117.6277  12039750.0   65.97648   1627266.0         NaN   
3       21125760.0  117.6283  12040130.0   65.97669   1627290.0         NaN   
4       21125860.0  117.6290  12040520.0   65.97691   1627313.0         NaN   
...            ...       ...         ...        ...         ...         ...   
271703   8721603.0  109.4972   2195037.0   68.44791   8454861.0         NaN   
271704   8721549.0  109.4979   2195037.0   68.44791   8454861.0         NaN   
271705   8721495.0  109.4987   2195037.0   68.44791   8454861.0         NaN   
271706   8721441.0  109.4994   2195037.0   68.44791   8454861.0         NaN   
271707   8721387.0  109.5001   2195037.0   68.44791   8454861.0         NaN   

        QGL  class  
0       0.0    0.0  
1       0.0    0.0  
2       0.0    0.0  
3       0.0    0.0  
4       0.0    0.0  
...     ...    ...  
271703  0.0  107.0  
271704  0.0  107.0  
271705  0.0  107.0  
271706  0.0  107.0  
271707  0.0  107.0  

[271708 rows x 12 columns]

In [24]:
df.dropna()
#clean dataset to remove name, id, timestamp
df=df.drop(['name','id','timestamp', 'T-JUS-CKGL'],axis=1)

#replace all NaN with 0
# df=df.fillna(0)

# drop all rows with class NaN
df=df.dropna(subset=['class'])

# print NaN in any column

# drop all rows where P-PDG is NaN
df=df.dropna(subset=['P-PDG'])

print(df[df.isna().any(axis=1)])



Empty DataFrame
Columns: [P-PDG, P-TPT, T-TPT, P-MON-CKP, T-JUS-CKP, P-JUS-CKGL, QGL, class]
Index: []


In [25]:
# show all values in column class
print(df['class'].unique())

# print 5 rows where class = NaN
print(df[df['class'].isna()].head())

#count number of 0, 3 in class label
print("count of 0 in class label: ",len(df[df['class']==0])) # normal state
print("count of NaN in class label: ",len(df[df['class'].isna()])) # normal state
print("count of 7 in class label: ",len(df[df['class']==7]))  # warning state
print("count of 107 in class label: ",len(df[df['class']==107]))  # error state


[  0. 107.   7.]
Empty DataFrame
Columns: [P-PDG, P-TPT, T-TPT, P-MON-CKP, T-JUS-CKP, P-JUS-CKGL, QGL, class]
Index: []
count of 0 in class label:  12526
count of NaN in class label:  0
count of 7 in class label:  821
count of 107 in class label:  257366


In [26]:
#split dataset into train and test
from sklearn.model_selection import train_test_split
X=df.drop(['class'],axis=1)
y=df['class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

### Generate Models

#### Logistic Regression

In [27]:
#train logistic regression model on training set against class label
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler

# scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#train model on training set
log_reg=LogisticRegression(max_iter=100000)
log_reg.fit(X_train_scaled,y_train)

#predict class label on training set
logreg_train_set_predictions=log_reg.predict(X_train_scaled)

#test model on test set
logreg_test_set_predictions=log_reg.predict(X_test_scaled)
log_accuracy=accuracy_score(y_test,logreg_test_set_predictions)
log_confusion_matrix=confusion_matrix(y_test,logreg_test_set_predictions)
log_classification_report=classification_report(y_test,logreg_test_set_predictions)


In [28]:
print("log_accuracy\n",log_accuracy)
print(log_confusion_matrix)
print(log_classification_report)
print("log_accuracy = %.1f"%(log_accuracy*100),"%")

log_accuracy
 0.9526254548141034
[[  178     0  2368]
 [    0     7   155]
 [   42     0 51393]]
              precision    recall  f1-score   support

         0.0       0.81      0.07      0.13      2546
         7.0       1.00      0.04      0.08       162
       107.0       0.95      1.00      0.98     51435

    accuracy                           0.95     54143
   macro avg       0.92      0.37      0.40     54143
weighted avg       0.95      0.95      0.93     54143

log_accuracy = 95.3 %


#### Decision Tree

In [29]:
#train decision tree regression model on training set against class label
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

X_train = np.nan_to_num(X_train.astype(np.float64))
X_test = np.nan_to_num(X_test.astype(np.float64))

# check for infinite or NaN values in X_train and X_test
if not np.isfinite(X_train).all() or not np.isfinite(X_test).all():
    print("Input data contains infinite or NaN values.")

#train model on training set
dt_reg=DecisionTreeRegressor()
dt_reg.fit(X_train,y_train)

#predict class label on training set
dectree_train_set_predictions=dt_reg.predict(X_train)

#test model on test set
dectree_test_set_predictions=dt_reg.predict(X_test)
dt_mse=mean_squared_error(y_test,dectree_test_set_predictions)
dt_rmse=np.sqrt(dt_mse)
dt_accuracy=accuracy_score(y_test,dectree_test_set_predictions)
dt_confusion_matrix=confusion_matrix(y_test,dectree_test_set_predictions)


/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/sklearn/utils/_array_api.py:380: RuntimeWarning: overflow encountered in cast
  array = numpy.asarray(array, order=order, dtype=dtype)


ValueError: Input X contains infinity or a value too large for dtype('float32').

In [ ]:
print("dt_mse\n",dt_mse)
print("dt_rmse\n",dt_rmse)
print("dt_accuracy\n",dt_accuracy)
print(dt_confusion_matrix)
print("dt_accuracy = %.1f"%(dt_accuracy*100),"%")


## Review

In [ ]:
print()