# BC2406 Project

3 types:
* lin reg
* logistic reg
* CART (dec tree)

## Dataset 1

### Data Handling

In [30]:
import glob
import os
import pandas as pd
import numpy as np

#import csv files
# print(csv_files)
path=os.path.join(os.getcwd(),'data','1')
csv_files=glob.glob(path + "/*.csv")

#remove BC2406.ipynb from csv_files
# csv_files.remove('BC2406.ipynb')

# remove all files whose file name (not path) starts with SIMULATED
csv_files=[csv_file for csv_file in csv_files if not os.path.basename(csv_file).startswith('SIMULATED')]

dataframes={}

print(csv_files)
for csv_file in csv_files:
  # print(csv_file)
  well_name=os.path.splitext(csv_file)[0]
  # print("file path")
  # print(os.path.join(csv_directory,csv_file))

  df = pd.read_csv(csv_file)
  # df_test = pd.read_csv(csv_file, nrows=100)

  # float_cols = [c for c in df_test if df_test[c].dtype == "float64"]
  # float32_cols = {c: np.float32 for c in float_cols}

  # df=pd.read_csv(csv_file, engine='c', dtype=float32_cols)
  dataframes[well_name]=df

for well_name,df in dataframes.items():
  df.insert(0,'name',well_name.split('_')[0].split('/')[-1])
  df.insert(1,'id',well_name.split('_')[1])

df=pd.concat(dataframes.values(),ignore_index=True)

distinct_wells=df['name'].unique()
for name in distinct_wells:
  print(name)

df

[]


ValueError: No objects to concatenate

In [ ]:
df.agg(['min', 'max'])

name              id                   timestamp         P-PDG  \
min       DRAWN           00001  2014-01-24 21:31:36.000000 -1.180116e+42   
max  WELL-00006  20180618060245  2018-09-07 20:44:35.000000  4.485805e+07   

            P-TPT       T-TPT     P-MON-CKP  T-JUS-CKP  P-JUS-CKGL  \
min  1.907455e+01    5.710797  1.004756e+01   30.03085   -300917.8   
max  2.078746e+07  123.600300  1.011330e+07  173.09610   4600253.0   

     T-JUS-CKGL  QGL  class  
min         NaN  0.0    0.0  
max         NaN  0.0  101.0

In [ ]:
# print rows where P-PDG is less than 1e+07
df[df['P-PDG']<-1e+07]

name              id                   timestamp         P-PDG  \
59256  WELL-00006  20180618060245  2018-06-18 06:02:45.000000 -1.180116e+42   
59257  WELL-00006  20180618060245  2018-06-18 06:02:46.000000 -1.180116e+42   
59258  WELL-00006  20180618060245  2018-06-18 06:02:47.000000 -1.180116e+42   
59259  WELL-00006  20180618060245  2018-06-18 06:02:48.000000 -1.180116e+42   
59260  WELL-00006  20180618060245  2018-06-18 06:02:49.000000 -1.180116e+42   
...           ...             ...                         ...           ...   
76216  WELL-00006  20180618060245  2018-06-18 10:45:25.000000 -1.180116e+42   
76217  WELL-00006  20180618060245  2018-06-18 10:45:26.000000 -1.180116e+42   
76218  WELL-00006  20180618060245  2018-06-18 10:45:27.000000 -1.180116e+42   
76219  WELL-00006  20180618060245  2018-06-18 10:45:28.000000 -1.180116e+42   
76220  WELL-00006  20180618060245  2018-06-18 10:45:29.000000 -1.180116e+42   

            P-TPT     T-TPT   P-MON-CKP  T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  \
59256  20787460.0  117.9124  10085640.0   70.86996   4096358.0         NaN   
59257  20787460.0  117.9123  10085720.0   70.86991   4096360.0         NaN   
59258  20787460.0  117.9122  10085810.0   70.86987   4096363.0         NaN   
59259  20787460.0  117.9120  10085930.0   70.86981   4096365.0         NaN   
59260  20787460.0  117.9119  10086050.0   70.86977   4096367.0         NaN   
...           ...       ...         ...        ...         ...         ...   
76216  20619450.0  118.2390   9992133.0   71.26657   4108511.0         NaN   
76217  20619480.0  118.2390   9992676.0   71.26487   4108512.0         NaN   
76218  20619520.0  118.2390   9993218.0   71.26317   4108512.0         NaN   
76219  20619550.0  118.2390   9993761.0   71.26147   4108512.0         NaN   
76220  20619590.0  118.2390   9994304.0   71.25977   4108513.0         NaN   

       QGL  class  
59256  0.0    0.0  
59257  0.0    0.0  
59258  0.0    0.0  
59259  0.0    0.0  
59260  0.0    0.0  
...    ...    ...  
76216  0.0  101.0  
76217  0.0  101.0  
76218  0.0  101.0  
76219  0.0  101.0  
76220  0.0  101.0  

[16965 rows x 12 columns]

In [ ]:
# convert df columns with float64 to float32
float_cols = [c for c in df if df[c].dtype == "float64"]
float32_cols = {c: np.float32 for c in float_cols}
df=df.astype(float32_cols)
df.agg(["min", "max"])

/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/pandas/core/dtypes/astype.py:134: RuntimeWarning: overflow encountered in cast
  return arr.astype(dtype, copy=True)


name              id                   timestamp       P-PDG  \
min       DRAWN           00001  2014-01-24 21:31:36.000000        -inf   
max  WELL-00006  20180618060245  2018-09-07 20:44:35.000000  44858048.0   

            P-TPT       T-TPT     P-MON-CKP   T-JUS-CKP    P-JUS-CKGL  \
min  1.907455e+01    5.710797  1.004756e+01   30.030849 -3.009178e+05   
max  2.078746e+07  123.600304  1.011330e+07  173.096100  4.600253e+06   

     T-JUS-CKGL  QGL  class  
min         NaN  0.0    0.0  
max         NaN  0.0  101.0

In [ ]:
# replace all values of P-PDG less than -1e+07 with -1e+07
df.loc[df['P-PDG']<-1e+07,'P-PDG']=-1e+07

df.agg(["min", "max"])

name              id                   timestamp       P-PDG  \
min       DRAWN           00001  2014-01-24 21:31:36.000000 -10000000.0   
max  WELL-00006  20180618060245  2018-09-07 20:44:35.000000  44858048.0   

            P-TPT       T-TPT     P-MON-CKP   T-JUS-CKP    P-JUS-CKGL  \
min  1.907455e+01    5.710797  1.004756e+01   30.030849 -3.009178e+05   
max  2.078746e+07  123.600304  1.011330e+07  173.096100  4.600253e+06   

     T-JUS-CKGL  QGL  class  
min         NaN  0.0    0.0  
max         NaN  0.0  101.0

In [ ]:
# show all values in column class
print(df['class'].unique())

#count number of 0, 3 in class label
print("count of 0 in class label: ",len(df[df['class']==0])) # normal state
print("count of 1 in class label: ",len(df[df['class']==1]))  # warning state
print("count of 101 in class label: ",len(df[df['class']==101]))  # warning state

[  0. 101.   1.  nan]
count of 0 in class label:  119319
count of 1 in class label:  33261
count of 101 in class label:  511895


In [ ]:
df.dropna()
#clean dataset to remove name, id, timestamp
df=df.drop(['name','id','timestamp'],axis=1)

df=df.fillna(0)

df.replace([np.inf, -np.inf], 0, inplace=True)

In [ ]:
#split dataset into train and test
from sklearn.model_selection import train_test_split
X=df.drop(['class'],axis=1)
y=df['class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
print(df.dtypes)

P-PDG         float32
P-TPT         float32
T-TPT         float32
P-MON-CKP     float32
T-JUS-CKP     float32
P-JUS-CKGL    float32
T-JUS-CKGL    float32
QGL           float32
class         float32
dtype: object


#### Logistic Regression

In [19]:
#train logistic regression model on training set against class label
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

#train model on training set
log_reg=LogisticRegression(max_iter=10000)
log_reg.fit(X_train,y_train)

#predict class label on training set
logreg_train_set_predictions=log_reg.predict(X_train)

#test model on test set
logreg_test_set_predictions=log_reg.predict(X_test)
log_accuracy=accuracy_score(y_test,logreg_test_set_predictions)
log_confusion_matrix=confusion_matrix(y_test,logreg_test_set_predictions)
log_classification_report=classification_report(y_test,logreg_test_set_predictions)

print("log_accuracy\n",log_accuracy)
print(log_confusion_matrix)
print(log_classification_report)
print("log_accuracy = %.1f"%(log_accuracy*100),"%")

log_accuracy
 0.04702362262896404
[[ 2546     0     0]
 [  162     0     0]
 [51435     0     0]]
              precision    recall  f1-score   support

         0.0       0.05      1.00      0.09      2546
         7.0       0.00      0.00      0.00       162
       107.0       0.00      0.00      0.00     51435

    accuracy                           0.05     54143
   macro avg       0.02      0.33      0.03     54143
weighted avg       0.00      0.05      0.00     54143

log_accuracy = 4.7 %


/Users/jamiegoh/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/jamiegoh/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/jamiegoh/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-d

#### Decision Tree

In [20]:
#train decision tree regression model on training set against class label
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import numpy as np

print(X_train.dtypes)

#train model on training set
dt_class=DecisionTreeClassifier()
dt_class.fit(X_train,y_train)


#predict class label on training set
dectree_train_set_predictions=dt_class.predict(X_train)

#test model on test set
dectree_test_set_predictions=dt_class.predict(X_test)
dt_mse=mean_squared_error(y_test,dectree_test_set_predictions)
dt_rmse=np.sqrt(dt_mse)
dt_accuracy=accuracy_score(y_test,dectree_test_set_predictions)
dt_confusion_matrix=confusion_matrix(y_test,dectree_test_set_predictions)

print("dt_mse\n",dt_mse)
print("dt_rmse\n",dt_rmse)
print("dt_accuracy\n",dt_accuracy)
print(dt_confusion_matrix)
print("dt_accuracy = %.1f"%(dt_accuracy*100),"%")

P-PDG         float64
P-TPT         float64
T-TPT         float64
P-MON-CKP     float64
T-JUS-CKP     float64
P-JUS-CKGL    float64
QGL           float64
dtype: object


ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

## Dataset 3

### Data Handling

In [ ]:
import glob
import os
import pandas as pd

#import csv files
# print(csv_files)
path=os.path.join(os.getcwd(),'data','3')
csv_files=glob.glob(path + "/*.csv")

#remove BC2406.ipynb from csv_files
# csv_files.remove('BC2406.ipynb')

# remove all files whose file name (not path) starts with SIMULATED
csv_files=[csv_file for csv_file in csv_files if not os.path.basename(csv_file).startswith('SIMULATED')]

dataframes={}

print(csv_files)
for csv_file in csv_files:
  # print(csv_file)
  well_name=os.path.splitext(csv_file)[0]
  # print("file path")
  # print(os.path.join(csv_directory,csv_file))
  df=pd.read_csv(csv_file)
  dataframes[well_name]=df

for well_name,df in dataframes.items():
  df.insert(0,'name',well_name.split('_')[0].split('/')[-1])
  df.insert(1,'id',well_name.split('_')[1])

df=pd.concat(dataframes.values(),ignore_index=True)

distinct_wells=df['name'].unique()
for name in distinct_wells:
  print(name)

df

['/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-00014_20170921200114.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-00014_20170925160218.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-00014_20170926170228.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-00014_20170920010042.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-00014_20170920060228.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-00014_20170921050404.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-00014_20170921100155.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-00001_20170320130025.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/3/WELL-

WELL-00014
WELL-00001


name              id                   timestamp       P-PDG  \
0       WELL-00014  20170921200114  2017-09-21 20:01:14.000000  24389400.0   
1       WELL-00014  20170921200114  2017-09-21 20:01:15.000000  24388900.0   
2       WELL-00014  20170921200114  2017-09-21 20:01:16.000000  24388410.0   
3       WELL-00014  20170921200114  2017-09-21 20:01:17.000000  24388120.0   
4       WELL-00014  20170921200114  2017-09-21 20:01:18.000000  24387820.0   
...            ...             ...                         ...         ...   
569147  WELL-00014  20170917150000  2017-09-17 19:56:11.000000  23525310.0   
569148  WELL-00014  20170917150000  2017-09-17 19:56:12.000000  23525260.0   
569149  WELL-00014  20170917150000  2017-09-17 19:56:13.000000  23525200.0   
569150  WELL-00014  20170917150000  2017-09-17 19:56:14.000000  23525150.0   
569151  WELL-00014  20170917150000  2017-09-17 19:56:15.000000  23525100.0   

             P-TPT     T-TPT  P-MON-CKP  T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  \
0       15923800.0  43.65952  1490977.0   31.00947  19415620.0         NaN   
1       15923280.0  43.65860  1492114.0   31.00781  19415860.0         NaN   
2       15922750.0  43.65767  1493250.0   31.00614  19416100.0         NaN   
3       15921120.0  43.65464  1494386.0   31.00448  19416350.0         NaN   
4       15919480.0  43.65160  1495523.0   31.00282  19416590.0         NaN   
...            ...       ...        ...        ...         ...         ...   
569147  13954990.0  56.54493  1893704.0   38.29067  19560470.0         NaN   
569148  13955230.0  56.54481  1894765.0   38.29134  19561440.0         NaN   
569149  13955470.0  56.54469  1895825.0   38.29200  19562410.0         NaN   
569150  13955710.0  56.54458  1896431.0   38.29267  19563380.0         NaN   
569151  13955950.0  56.54446  1897037.0   38.29333  19564350.0         NaN   

             QGL  class  
0       1.243595      3  
1       1.239152      3  
2       1.234708      3  
3       1.230265      3  
4       1.225821      3  
...          ...    ...  
569147  1.265560      3  
569148  1.278255      3  
569149  1.290949      3  
569150  1.303643      3  
569151  1.316338      3  

[569152 rows x 12 columns]

In [ ]:
# show all values in column class
print(df['class'].unique())

#count number of 0, 3 in class label
print("count of 0 in class label: ",len(df[df['class']==0])) # normal state
print("count of 3 in class label: ",len(df[df['class']==3]))  # warning state

[3]
count of 0 in class label:  0
count of 3 in class label:  569152


In [ ]:
df.dropna()
#clean dataset to remove name, id, timestamp
df=df.drop(['name','id','timestamp'],axis=1)

df=df.fillna(0)



In [ ]:
#split dataset into train and test
from sklearn.model_selection import train_test_split
X=df.drop(['class'],axis=1)
y=df['class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

### Generate Models

#### Logistic Regression

In [ ]:
# #train logistic regression model on training set against class label
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import accuracy_score
# from sklearn.metrics import confusion_matrix
# from sklearn.metrics import classification_report

# #train model on training set
# log_reg=LogisticRegression(max_iter=1000)
# log_reg.fit(X_train,y_train)

# #predict class label on training set
# logreg_train_set_predictions=log_reg.predict(X_train)

# #test model on test set
# logreg_test_set_predictions=log_reg.predict(X_test)
# log_accuracy=accuracy_score(y_test,logreg_test_set_predictions)
# log_confusion_matrix=confusion_matrix(y_test,logreg_test_set_predictions)
# log_classification_report=classification_report(y_test,logreg_test_set_predictions)




#### Decision Tree

In [21]:
#train decision tree regression model on training set against class label
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

#train model on training set
dt_class=DecisionTreeClassifier()
dt_class.fit(X_train,y_train)

#predict class label on training set
dectree_train_set_predictions=dt_class.predict(X_train)

#test model on test set
dectree_test_set_predictions=dt_class.predict(X_test)
dt_mse=mean_squared_error(y_test,dectree_test_set_predictions)
dt_rmse=np.sqrt(dt_mse)
dt_accuracy=accuracy_score(y_test,dectree_test_set_predictions)
dt_confusion_matrix=confusion_matrix(y_test,dectree_test_set_predictions)

print("dt_mse\n",dt_mse)
print("dt_rmse\n",dt_rmse)
print("dt_accuracy\n",dt_accuracy)
print(dt_confusion_matrix)
print("dt_accuracy = %.1f"%(dt_accuracy*100),"%")

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

## Dataset 5 (Rapid Productivity Loss)

### Data Handling

In [ ]:
import glob
import os
import pandas as pd

#import csv files
# print(csv_files)
path=os.path.join(os.getcwd(),'data','5')
csv_files=glob.glob(path + "/*.csv")

#remove BC2406.ipynb from csv_files
# csv_files.remove('BC2406.ipynb')

dataframes={}

print(csv_files)
for csv_file in csv_files:
  # print(csv_file)
  well_name=os.path.splitext(csv_file)[0]
  # print("file path")
  # print(os.path.join(csv_directory,csv_file))
  df=pd.read_csv(csv_file)
  dataframes[well_name]=df

for well_name,df in dataframes.items():
  df.insert(0,'name',well_name.split('_')[0])
  df.insert(1,'id',well_name.split('_')[1])

df=pd.concat(dataframes.values(),ignore_index=True)

distinct_wells=df['name'].unique()
for name in distinct_wells:
  print(name)

df





['/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00015_20171013140047.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00016_20180517222322.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00017_20140319141450.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00016_20180405020345.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00016_20180426142005.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00017_20140318160220.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00015_20170620160349.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00017_20140314180000.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-

/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00015
/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00016
/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/5/WELL-00017


name              id  \
0       /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
1       /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
2       /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
3       /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
4       /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
...                                                   ...             ...   
361993  /Users/dyllon/Library/Mobile Documents/com~app...  20180426145108   
361994  /Users/dyllon/Library/Mobile Documents/com~app...  20180426145108   
361995  /Users/dyllon/Library/Mobile Documents/com~app...  20180426145108   
361996  /Users/dyllon/Library/Mobile Documents/com~app...  20180426145108   
361997  /Users/dyllon/Library/Mobile Documents/com~app...  20180426145108   

                         timestamp       P-PDG       P-TPT     T-TPT  \
0       2017-10-13 14:00:47.000000  23639730.0         0.0   0.00000   
1       2017-10-13 14:00:48.000000  23640270.0         0.0   0.00000   
2       2017-10-13 14:00:49.000000  23640810.0         0.0   0.00000   
3       2017-10-13 14:00:50.000000  23641350.0         0.0   0.00000   
4       2017-10-13 14:00:51.000000  23641890.0         0.0   0.00000   
...                            ...         ...         ...       ...   
361993  2018-04-26 15:44:16.000000  24660500.0  11091050.0  16.99739   
361994  2018-04-26 15:44:17.000000  24660460.0  11091230.0  16.99959   
361995  2018-04-26 15:44:18.000000  24660420.0  11091420.0  17.00179   
361996  2018-04-26 15:44:19.000000  24660380.0  11091610.0  17.00399   
361997  2018-04-26 15:44:20.000000  24660340.0  11091800.0  17.00619   

        P-MON-CKP  T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL       QGL  class  
0       3509006.0   42.35576  19960610.0         NaN  1.288151    0.0  
1       3483324.0   42.35957  19978070.0         NaN  1.291373    0.0  
2       3449990.0   42.36337  19995540.0         NaN  1.294595    0.0  
3       3416657.0   42.36717  20013010.0         NaN  1.297816    0.0  
4       3383324.0   42.37098  20030480.0         NaN  1.302506    0.0  
...           ...        ...         ...         ...       ...    ...  
361993   845799.3   50.32685  18913280.0         NaN  1.766007    5.0  
361994   845819.6   50.32632  18913740.0         NaN  1.736611    5.0  
361995   845840.0   50.32579  18914190.0         NaN  1.707214    5.0  
361996   845860.3   50.32526  18914650.0         NaN  1.677818    5.0  
361997   845880.7   50.32472  18915110.0         NaN  1.648421    5.0  

[361998 rows x 12 columns]

In [ ]:
df.head()

name              id  \
0  /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
1  /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
2  /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
3  /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   
4  /Users/dyllon/Library/Mobile Documents/com~app...  20171013140047   

                    timestamp       P-PDG  P-TPT  T-TPT  P-MON-CKP  T-JUS-CKP  \
0  2017-10-13 14:00:47.000000  23639730.0    0.0    0.0  3509006.0   42.35576   
1  2017-10-13 14:00:48.000000  23640270.0    0.0    0.0  3483324.0   42.35957   
2  2017-10-13 14:00:49.000000  23640810.0    0.0    0.0  3449990.0   42.36337   
3  2017-10-13 14:00:50.000000  23641350.0    0.0    0.0  3416657.0   42.36717   
4  2017-10-13 14:00:51.000000  23641890.0    0.0    0.0  3383324.0   42.37098   

   P-JUS-CKGL  T-JUS-CKGL       QGL  class  
0  19960610.0         NaN  1.288151    0.0  
1  19978070.0         NaN  1.291373    0.0  
2  19995540.0         NaN  1.294595    0.0  
3  20013010.0         NaN  1.297816    0.0  
4  20030480.0         NaN  1.302506    0.0

In [ ]:
df.dropna()
#clean dataset to remove name, id, timestamp
df=df.drop(['name','id','timestamp'],axis=1)

#replace all NaN with 0
df=df.fillna(0)


In [ ]:
#count number of 0, 5 and 105 in class label
print("count of 0 in class label",len(df[df['class']==0])) # normal state
print("count of 5 in class label",len(df[df['class']==5]))  # warning state
print("count of 105 in class label",len(df[df['class']==105])) # abnormal state


count of 0 in class label 33693
count of 5 in class label 10147
count of 105 in class label 318158


In [ ]:
#split dataset into train and test
from sklearn.model_selection import train_test_split
X=df.drop(['class'],axis=1)
y=df['class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
print

### Generate Models

#### Logistic Regression

In [ ]:
#train logistic regression model on training set against class label
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

#train model on training set
log_reg=LogisticRegression(max_iter=1000)
log_reg.fit(X_train,y_train)

#predict class label on training set
logreg_train_set_predictions=log_reg.predict(X_train)

#test model on test set
logreg_test_set_predictions=log_reg.predict(X_test)
log_accuracy=accuracy_score(y_test,logreg_test_set_predictions)
log_confusion_matrix=confusion_matrix(y_test,logreg_test_set_predictions)
log_classification_report=classification_report(y_test,logreg_test_set_predictions)




In [ ]:
print("log_accuracy\n",log_accuracy)
print(log_confusion_matrix)
print(log_classification_report)
print("log_accuracy = %.1f"%(log_accuracy*100),"%")


log_accuracy
 0.8598066298342542
[[  402   415  5987]
 [    0   659  1324]
 [  867  1557 61189]]
              precision    recall  f1-score   support

         0.0       0.32      0.06      0.10      6804
         5.0       0.25      0.33      0.29      1983
       105.0       0.89      0.96      0.93     63613

    accuracy                           0.86     72400
   macro avg       0.49      0.45      0.44     72400
weighted avg       0.82      0.86      0.83     72400

log_accuracy = 86.0 %


#### Decision Tree

In [25]:
#train decision tree regression model on training set against class label
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error
import numpy as np

#train model on training set
# print(X_train.dtypes)

dt_class=DecisionTreeClassifier()
dt_class.fit(X_train,y_train)

#predict class label on training set
dectree_train_set_predictions=dt_class.predict(X_train)

#test model on test set
dectree_test_set_predictions=dt_class.predict(X_test)
dt_mse=mean_squared_error(y_test,dectree_test_set_predictions)
dt_rmse=np.sqrt(dt_mse)
dt_accuracy=accuracy_score(y_test,dectree_test_set_predictions)
dt_confusion_matrix=confusion_matrix(y_test,dectree_test_set_predictions)



In [ ]:
print("dt_mse\n",dt_mse)
print("dt_rmse\n",dt_rmse)
print("dt_accuracy\n",dt_accuracy)
print(dt_confusion_matrix)
print("dt_accuracy = %.1f"%(dt_accuracy*100),"%")


dt_mse
 0.762085635359116
dt_rmse
 0.8729751630826137
dt_accuracy
 0.999903314917127
[[ 6800     1     3]
 [    1  1982     0]
 [    2     0 63611]]
dt_accuracy = 100.0 %


#### xgboost

In [ ]:
import xgboost as xgb
import numpy as np
from sklearn.preprocessing import LabelEncoder



In [ ]:
le = LabelEncoder()
y_trainLE = le.fit_transform(y_train)

In [ ]:
xgb_class=xgb.XGBClassifier()
xgb_class.fit(X_train,y_trainLE)

#predict class label on training set
xgb_train_set_predictions=xgb_class.predict(X_train)

#test model on test set
y_pred=xgb_class.predict(X_test)



In [ ]:
#train logistic regression model on training set against class label
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

#convert y_pred to 0,5,105
y_pred=np.round(y_pred)
y_pred=le.inverse_transform(y_pred.astype(int))

xgb_accuracy=accuracy_score(y_test,y_pred)
xgb_confusion_matrix=confusion_matrix(y_test,y_pred)
xgb_classification_report=classification_report(y_test,y_pred)

print("xgb_accuracy\n",xgb_accuracy)
print(xgb_confusion_matrix)
print(xgb_classification_report)


xgb_accuracy
 0.9997651933701658
[[ 6793     6     5]
 [    0  1983     0]
 [    6     0 63607]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      6804
         5.0       1.00      1.00      1.00      1983
       105.0       1.00      1.00      1.00     63613

    accuracy                           1.00     72400
   macro avg       1.00      1.00      1.00     72400
weighted avg       1.00      1.00      1.00     72400



In [ ]:
# %pip install --no-build-isolation catboost

#### CatBoost

In [ ]:
from catboost import CatBoostClassifier


In [ ]:
le = LabelEncoder()
y_trainLE = le.fit_transform(y_train)

In [ ]:


cat_reg=CatBoostClassifier()
cat_reg.fit(X_train,y_trainLE)

#predict class label on training set
cat_train_set_predictions=cat_reg.predict(X_train)

#test model on test set
cat_test_set_predictions=cat_reg.predict(X_test)


Learning rate set to 0.105651
0:	learn: 0.9236072	total: 59.6ms	remaining: 59.6s
1:	learn: 0.7914485	total: 100ms	remaining: 49.9s
2:	learn: 0.6879227	total: 133ms	remaining: 44.3s
3:	learn: 0.6063271	total: 165ms	remaining: 41.2s
4:	learn: 0.5346120	total: 210ms	remaining: 41.8s
5:	learn: 0.4746592	total: 285ms	remaining: 47.3s
6:	learn: 0.4235376	total: 328ms	remaining: 46.5s
7:	learn: 0.3807083	total: 361ms	remaining: 44.7s
8:	learn: 0.3422057	total: 394ms	remaining: 43.4s
9:	learn: 0.3083072	total: 434ms	remaining: 42.9s
10:	learn: 0.2802932	total: 474ms	remaining: 42.7s
11:	learn: 0.2546340	total: 509ms	remaining: 41.9s
12:	learn: 0.2324941	total: 546ms	remaining: 41.4s
13:	learn: 0.2125383	total: 587ms	remaining: 41.3s
14:	learn: 0.1946054	total: 640ms	remaining: 42s
15:	learn: 0.1786510	total: 694ms	remaining: 42.7s
16:	learn: 0.1657458	total: 736ms	remaining: 42.5s
17:	learn: 0.1552057	total: 776ms	remaining: 42.3s
18:	learn: 0.1437041	total: 825ms	remaining: 42.6s
19:	learn: 0

In [ ]:
#convert y_pred to 0,5,105
cat_test_set_predictions=np.round(cat_test_set_predictions)
cat_test_set_predictions=le.inverse_transform(cat_test_set_predictions.astype(int))

cat_accuracy=accuracy_score(y_test,cat_test_set_predictions)
cat_confusion_matrix=confusion_matrix(y_test,cat_test_set_predictions)

print("cat_accuracy\n",cat_accuracy)
print(cat_confusion_matrix)
print(xgb_classification_report)

cat_accuracy
 0.9996961325966851
[[ 6791     5     8]
 [    0  1983     0]
 [    9     0 63604]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      6804
         5.0       1.00      1.00      1.00      1983
       105.0       1.00      1.00      1.00     63613

    accuracy                           1.00     72400
   macro avg       1.00      1.00      1.00     72400
weighted avg       1.00      1.00      1.00     72400



/Users/jamiegoh/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


#### LightGBM

In [ ]:
# %pip install --upgrade lightgbm

In [ ]:
import lightgbm as lgb


In [ ]:
# #train lightgbm regression model on training set against class label


# le = LabelEncoder()
# y_trainLE = le.fit_transform(y_train)

lgb_reg=lgb.LGBMRegressor()
lgb_reg.fit(X_train,y_train)

#predict class label on training set
lgb_train_set_predictions=lgb_reg.predict(X_train)

#test model on test set
lgb_test_set_predictions=lgb_reg.predict(X_test)





[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004580 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1785
[LightGBM] [Info] Number of data points in the train set: 289598, number of used features: 7
[LightGBM] [Info] Start training from score 92.431733


In [ ]:
import numpy as np

In [ ]:
lgb_test_set_predictions=np.round(lgb_test_set_predictions)
lgb_test_set_predictions=le.inverse_transform(lgb_test_set_predictions.astype(int))

lgb_accuracy=accuracy_score(y_test,lgb_test_set_predictions)
lgb_confusion_matrix=confusion_matrix(y_test,lgb_test_set_predictions)
lgb_classification_report=classification_report(y_test,lgb_test_set_predictions)

print("lgb_accuracy\n",lgb_accuracy)
print(lgb_confusion_matrix)
print(xgb_classification_report)

ValueError: y contains previously unseen labels: [-15 -12 -11 -10  -9  -6  -5  -4  -3  -2  -1   3   4   5   6   7   8   9
  10  11  12  13  14  15  16  17  18  19  20  22  23  24  25  26  27  28
  29  32  33  37  38  40  42  43  44  48  49  51  54  56  57  58  59  60
  61  63  64  67  68  70  71  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 116 119 121]

### Compare Models

In [ ]:
# compare both models with f1 score
from sklearn.metrics import f1_score

# calculate F1 scores for both models
logreg_f1 = f1_score(y_test, logreg_test_set_predictions, average='weighted')
dectree_f1 = f1_score(y_test, dectree_test_set_predictions, average='weighted')

# print
print("F1 scores:")
print("Logistic Regression: ", logreg_f1)
print("Decision Tree Regressor: ", dectree_f1)

# compare F1 scores
if logreg_f1 > dectree_f1:
    print("Logistic Regression has a higher F1 score.")
elif logreg_f1 < dectree_f1:
    print("Decision Tree has a higher F1 score.")
else:
    print("Both models have the same F1 score.")




## Dataset 7

### Data Handling

In [1]:
import glob
import os
import pandas as pd

#import csv files
# print(csv_files)
path=os.path.join(os.getcwd(),'data','7')
csv_files=glob.glob(path + "/*.csv")

#remove BC2406.ipynb from csv_files
# csv_files.remove('BC2406.ipynb')

# remove all files whose file name (not path) starts with SIMULATED
csv_files=[csv_file for csv_file in csv_files if not os.path.basename(csv_file).startswith('DRAWN')]

dataframes={}

print(csv_files)
for csv_file in csv_files:
  # print(csv_file)
  well_name=os.path.splitext(csv_file)[0]
  # print("file path")
  # print(os.path.join(csv_directory,csv_file))
  df=pd.read_csv(csv_file)
  dataframes[well_name]=df

for well_name,df in dataframes.items():
  df.insert(0,'name',well_name.split('_')[0].split('/')[-1])
  df.insert(1,'id',well_name.split('_')[1])

df=pd.concat(dataframes.values(),ignore_index=True)

distinct_wells=df['name'].unique()
for name in distinct_wells:
  print(name)

df

['/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/7/WELL-00006_20180620181348.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/7/WELL-00006_20180618110721.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/7/WELL-00001_20170226220309.csv', '/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/oil/data/7/WELL-00018_20180611040207.csv']
WELL-00006
WELL-00001
WELL-00018


name              id                   timestamp         P-PDG  \
0       WELL-00006  20180620181348  2018-06-20 18:13:48.000000 -1.180116e+42   
1       WELL-00006  20180620181348  2018-06-20 18:13:49.000000 -1.180116e+42   
2       WELL-00006  20180620181348  2018-06-20 18:13:50.000000 -1.180116e+42   
3       WELL-00006  20180620181348  2018-06-20 18:13:51.000000 -1.180116e+42   
4       WELL-00006  20180620181348  2018-06-20 18:13:52.000000 -1.180116e+42   
...            ...             ...                         ...           ...   
271703  WELL-00018  20180611040207  2018-06-11 12:58:09.000000  0.000000e+00   
271704  WELL-00018  20180611040207  2018-06-11 12:58:10.000000  0.000000e+00   
271705  WELL-00018  20180611040207  2018-06-11 12:58:11.000000  0.000000e+00   
271706  WELL-00018  20180611040207  2018-06-11 12:58:12.000000  0.000000e+00   
271707  WELL-00018  20180611040207  2018-06-11 12:58:13.000000  0.000000e+00   

             P-TPT     T-TPT   P-MON-CKP  T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  \
0       21125440.0  117.6264  12038980.0   65.97606   1627220.0         NaN   
1       21125550.0  117.6270  12039360.0   65.97627   1627243.0         NaN   
2       21125650.0  117.6277  12039750.0   65.97648   1627266.0         NaN   
3       21125760.0  117.6283  12040130.0   65.97669   1627290.0         NaN   
4       21125860.0  117.6290  12040520.0   65.97691   1627313.0         NaN   
...            ...       ...         ...        ...         ...         ...   
271703   8721603.0  109.4972   2195037.0   68.44791   8454861.0         NaN   
271704   8721549.0  109.4979   2195037.0   68.44791   8454861.0         NaN   
271705   8721495.0  109.4987   2195037.0   68.44791   8454861.0         NaN   
271706   8721441.0  109.4994   2195037.0   68.44791   8454861.0         NaN   
271707   8721387.0  109.5001   2195037.0   68.44791   8454861.0         NaN   

        QGL  class  
0       0.0    0.0  
1       0.0    0.0  
2       0.0    0.0  
3       0.0    0.0  
4       0.0    0.0  
...     ...    ...  
271703  0.0  107.0  
271704  0.0  107.0  
271705  0.0  107.0  
271706  0.0  107.0  
271707  0.0  107.0  

[271708 rows x 12 columns]

In [2]:

#clean dataset to remove name, id, timestamp
df=df.drop(['name','id','timestamp', 'T-JUS-CKGL'],axis=1)

#replace all NaN with 0
# df=df.fillna(0)

# drop all rows with class NaN
df=df.dropna(subset=['class'])

# # print NaN in any column

# drop all rows where P-PDG is NaN
df=df.dropna(subset=['P-PDG'])

print(df[df.isna().any(axis=1)])




Empty DataFrame
Columns: [P-PDG, P-TPT, T-TPT, P-MON-CKP, T-JUS-CKP, P-JUS-CKGL, QGL, class]
Index: []


In [3]:
# show all values in column class
print(df['class'].unique())

# print 5 rows where class = NaN
print(df[df['class'].isna()].head())

#count number of 0, 3 in class label
print("count of 0 in class label: ",len(df[df['class']==0])) # normal state
print("count of NaN in class label: ",len(df[df['class'].isna()])) # NaN state
print("count of 7 in class label: ",len(df[df['class']==7]))  # warning state
print("count of 107 in class label: ",len(df[df['class']==107]))  # error state


[  0. 107.   7.]
Empty DataFrame
Columns: [P-PDG, P-TPT, T-TPT, P-MON-CKP, T-JUS-CKP, P-JUS-CKGL, QGL, class]
Index: []
count of 0 in class label:  12526
count of NaN in class label:  0
count of 7 in class label:  821
count of 107 in class label:  257366


In [4]:
#split dataset into train and test
from sklearn.model_selection import train_test_split
X=df.drop(['class'],axis=1)
y=df['class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

### Generate Models

#### Logistic Regression

In [5]:
#train logistic regression model on training set against class label
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler

# scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#train model on training set
log_reg=LogisticRegression(max_iter=100000)
log_reg.fit(X_train_scaled,y_train)

#predict class label on training set
logreg_train_set_predictions=log_reg.predict(X_train_scaled)

#test model on test set
logreg_test_set_predictions=log_reg.predict(X_test_scaled)
log_accuracy=accuracy_score(y_test,logreg_test_set_predictions)
log_confusion_matrix=confusion_matrix(y_test,logreg_test_set_predictions)
log_classification_report=classification_report(y_test,logreg_test_set_predictions)


In [8]:
print("log_accuracy\n",log_accuracy)
print(log_confusion_matrix)
print(log_classification_report)
print("log_accuracy = %.1f"%(log_accuracy*100),"%")

log_accuracy
 0.9526254548141034
[[  178     0  2368]
 [    0     7   155]
 [   42     0 51393]]
              precision    recall  f1-score   support

         0.0       0.81      0.07      0.13      2546
         7.0       1.00      0.04      0.08       162
       107.0       0.95      1.00      0.98     51435

    accuracy                           0.95     54143
   macro avg       0.92      0.37      0.40     54143
weighted avg       0.95      0.95      0.93     54143

log_accuracy = 95.3 %


#### Decision Tree

In [10]:
#train decision tree regression model on training set against class label
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error
import numpy as np

X_train = np.nan_to_num(X_train.astype(np.float32))
X_test = np.nan_to_num(X_test.astype(np.float32))

# check for infinite or NaN values in X_train and X_test
if not np.isfinite(X_train).all() or not np.isfinite(X_test).all():
    print("Input data contains infinite or NaN values.")

#train model on training set
dt_class=DecisionTreeClassifier()
dt_class.fit(X_train,y_train)

#predict class label on training set
dectree_train_set_predictions=dt_class.predict(X_train)

#test model on test set
dectree_test_set_predictions=dt_class.predict(X_test)
dt_mse=mean_squared_error(y_test,dectree_test_set_predictions)
dt_rmse=np.sqrt(dt_mse)
dt_accuracy=accuracy_score(y_test,dectree_test_set_predictions)
dt_confusion_matrix=confusion_matrix(y_test,dectree_test_set_predictions)


/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/pandas/core/dtypes/astype.py:134: RuntimeWarning: overflow encountered in cast
  return arr.astype(dtype, copy=True)
/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/pandas/core/dtypes/astype.py:134: RuntimeWarning: overflow encountered in cast
  return arr.astype(dtype, copy=True)


In [12]:
print("dt_mse\n",dt_mse)
print("dt_rmse\n",dt_rmse)
print("dt_accuracy\n",dt_accuracy)
print(dt_confusion_matrix)
print("dt_accuracy = %.1f"%(dt_accuracy*100),"%")


dt_mse
 0.18469608259608813
dt_rmse
 0.4297628213283324
dt_accuracy
 0.9999815303917404
[[ 2546     0     0]
 [    0   161     1]
 [    0     0 51435]]
dt_accuracy = 100.0 %


#### xgboost

In [13]:
#train xgboost regression model on training set against class label
import xgboost as xgb
import numpy as np
from sklearn.preprocessing import LabelEncoder

# scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

le = LabelEncoder()
y_trainLE = le.fit_transform(y_train)

xgb_class=xgb.XGBClassifier()
xgb_class.fit(X_train_scaled,y_trainLE)

#predict class label on training set
xgb_train_set_predictions=xgb_class.predict(X_train_scaled)

#test model on test set
y_pred=xgb_class.predict(X_test_scaled)

#convert y_pred
y_pred=np.round(y_pred)
y_pred=le.inverse_transform(y_pred.astype(int))

xgb_accuracy=accuracy_score(y_test,y_pred)
xgb_confusion_matrix=confusion_matrix(y_test,y_pred)
xgb_classification_report=classification_report(y_test,y_pred)

print("xgb_accuracy\n",xgb_accuracy)
print(xgb_confusion_matrix)
print(xgb_classification_report)

xgb_accuracy
 0.9994089725356925
[[ 2542     0     4]
 [    0   159     3]
 [   24     1 51410]]
              precision    recall  f1-score   support

         0.0       0.99      1.00      0.99      2546
         7.0       0.99      0.98      0.99       162
       107.0       1.00      1.00      1.00     51435

    accuracy                           1.00     54143
   macro avg       0.99      0.99      0.99     54143
weighted avg       1.00      1.00      1.00     54143



In [14]:
#DO NOT RUN - TAKES 100 MINS TO RUN

# #tune hyperparameters for xgboost
# from sklearn.model_selection import GridSearchCV

# # define parameters to tune
# parameters = {'max_depth': [3, 4, 5, 6, 7, 8, 9, 10], 'learning_rate': [0.01, 0.05, 0.1, 0.2, 0.3],
#             'n_estimators': [100, 200, 300, 400, 500]}
# xgb_class = xgb.XGBClassifier()

# # tune hyperparameters

# grid_search = GridSearchCV(xgb_class, parameters, cv=5, scoring='accuracy', return_train_score=True)
# grid_search.fit(X_train_scaled, y_trainLE)





In [16]:
# print best parameters
# print(grid_search.best_params_)

# print(grid_search.best_score_)


{'learning_rate': 0.05, 'max_depth': 4, 'n_estimators': 400}
0.999533638084684

In [17]:
#train xgboost regression model on training set against class label
import xgboost as xgb
import numpy as np
from sklearn.preprocessing import LabelEncoder

# scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

le = LabelEncoder()
y_trainLE = le.fit_transform(y_train)

xgb_class=xgb.XGBClassifier(
    learning_rate=0.05,
    max_depth=4,
    n_estimators=400,
)

xgb_class.fit(X_train_scaled,y_trainLE)

#predict class label on training set
xgb_train_set_predictions=xgb_class.predict(X_train_scaled)

#test model on test set
y_pred=xgb_class.predict(X_test_scaled)

#convert y_pred
y_pred=np.round(y_pred)
y_pred=le.inverse_transform(y_pred.astype(int))

xgb_accuracy=accuracy_score(y_test,y_pred)
xgb_confusion_matrix=confusion_matrix(y_test,y_pred)
xgb_classification_report=classification_report(y_test,y_pred)

print("xgb_accuracy\n",xgb_accuracy)
print(xgb_confusion_matrix)
print(xgb_classification_report)

xgb_accuracy
 0.9994274421439521
[[ 2544     0     2]
 [    0   159     3]
 [   25     1 51409]]
              precision    recall  f1-score   support

         0.0       0.99      1.00      0.99      2546
         7.0       0.99      0.98      0.99       162
       107.0       1.00      1.00      1.00     51435

    accuracy                           1.00     54143
   macro avg       0.99      0.99      0.99     54143
weighted avg       1.00      1.00      1.00     54143



#### catboost

In [18]:
# #train catboost regression model on training set against class label

# # scale the data
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_test_scaled = scaler.transform(X_test)

# le = LabelEncoder()
# y_trainLE = le.fit_transform(y_train)

# cat_reg=CatBoostClassifier()
# cat_reg.fit(X_train_scaled,y_trainLE)

# #predict class label on training set
# cat_train_set_predictions=cat_reg.predict(X_train_scaled)


# #test model on test set
# cat_test_set_predictions=cat_reg.predict(X_test_scaled)

# #convert y_pred
# cat_test_set_predictions=np.round(cat_test_set_predictions)
# cat_test_set_predictions=le.inverse_transform(cat_test_set_predictions.astype(int))

# cat_accuracy=accuracy_score(y_test,cat_test_set_predictions)
# cat_confusion_matrix=confusion_matrix(y_test,cat_test_set_predictions)
# cat_classification_report=classification_report(y_test,cat_test_set_predictions)



In [19]:
# print("cat_accuracy\n",cat_accuracy)
# print(cat_confusion_matrix)
# print(cat_classification_report)

In [20]:
# #tune hyperparameters for catboost
# from sklearn.model_selection import GridSearchCV

# # scale the data
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_test_scaled = scaler.transform(X_test)

# le = LabelEncoder()
# y_trainLE = le.fit_transform(y_train)

# cat_reg=CatBoostClassifier()

# # define the grid of hyperparameters to search
# search_space = {'iterations': [100, 200, 500],
#                 'learning_rate': [0.01, 0.05, 0.1],
#                 'depth': [3, 5, 7]}
# # define search
# grid_search = GridSearchCV(cat_reg, search_space, cv=5, scoring="accuracy", n_jobs=-1)
# # execute search
# grid_result = grid_search.fit(X_train_scaled, y_trainLE)
# # summarize result
# print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))



best params  
(via sklearn gridsearchcv):  
Best: 0.999372 using {'depth': 7, 'iterations': 500, 'learning_rate': 0.05}


In [21]:
# %pip install catboost
from catboost import CatBoostClassifier
#train catboost regression model on training set against class label

# scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

le = LabelEncoder()
y_trainLE = le.fit_transform(y_train)

cat_reg=CatBoostClassifier(
    iterations=500,
    learning_rate=0.5,
    depth=7
)
cat_reg.fit(X_train_scaled,y_trainLE)

#predict class label on training set
cat_train_set_predictions=cat_reg.predict(X_train_scaled)


#test model on test set
cat_test_set_predictions=cat_reg.predict(X_test_scaled)

#convert y_pred
cat_test_set_predictions=np.round(cat_test_set_predictions)
cat_test_set_predictions=le.inverse_transform(cat_test_set_predictions.astype(int))

cat_accuracy=accuracy_score(y_test,cat_test_set_predictions)
cat_confusion_matrix=confusion_matrix(y_test,cat_test_set_predictions)
cat_classification_report=classification_report(y_test,cat_test_set_predictions)

0:	learn: 0.3861038	total: 293ms	remaining: 2m 26s
1:	learn: 0.2189519	total: 494ms	remaining: 2m 3s
2:	learn: 0.1240743	total: 651ms	remaining: 1m 47s
3:	learn: 0.0788224	total: 834ms	remaining: 1m 43s
4:	learn: 0.0491858	total: 1.06s	remaining: 1m 44s
5:	learn: 0.0339245	total: 1.25s	remaining: 1m 42s
6:	learn: 0.0230531	total: 1.46s	remaining: 1m 42s
7:	learn: 0.0166981	total: 1.69s	remaining: 1m 43s
8:	learn: 0.0120986	total: 1.86s	remaining: 1m 41s
9:	learn: 0.0092694	total: 2.01s	remaining: 1m 38s
10:	learn: 0.0078769	total: 2.18s	remaining: 1m 36s
11:	learn: 0.0063803	total: 2.32s	remaining: 1m 34s
12:	learn: 0.0056869	total: 2.46s	remaining: 1m 32s
13:	learn: 0.0045628	total: 2.59s	remaining: 1m 29s
14:	learn: 0.0042310	total: 2.7s	remaining: 1m 27s
15:	learn: 0.0038234	total: 2.82s	remaining: 1m 25s
16:	learn: 0.0033371	total: 2.97s	remaining: 1m 24s
17:	learn: 0.0029969	total: 3.12s	remaining: 1m 23s
18:	learn: 0.0028679	total: 3.28s	remaining: 1m 22s
19:	learn: 0.0027808	tot

/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:153: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [22]:
print("cat_accuracy\n",cat_accuracy)
print(cat_confusion_matrix)
print(cat_classification_report)

cat_accuracy
 0.9990211107622408
[[ 2536     0    10]
 [    0   162     0]
 [   43     0 51392]]
              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      2546
         7.0       1.00      1.00      1.00       162
       107.0       1.00      1.00      1.00     51435

    accuracy                           1.00     54143
   macro avg       0.99      1.00      1.00     54143
weighted avg       1.00      1.00      1.00     54143



#### lightgbm

In [23]:

import lightgbm as lgb
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


# scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#train lightgbm regression model on training set against class label
le = LabelEncoder()
y_trainLE = le.fit_transform(y_train)

lgb_reg=lgb.LGBMClassifier()
lgb_reg.fit(X_train_scaled,y_trainLE)

#predict class label on training set
lgb_train_set_predictions=lgb_reg.predict(X_train_scaled)

#test model on test set
lgb_test_set_predictions=lgb_reg.predict(X_test_scaled)

#convert y_pred
lgb_test_set_predictions=np.round(lgb_test_set_predictions)
lgb_test_set_predictions=le.inverse_transform(lgb_test_set_predictions.astype(int))

lgb_accuracy=accuracy_score(y_test,lgb_test_set_predictions)
lgb_confusion_matrix=confusion_matrix(y_test,lgb_test_set_predictions)
lgb_classification_report=classification_report(y_test,lgb_test_set_predictions)

print("lgb_accuracy\n",lgb_accuracy)
print(lgb_confusion_matrix)
print(lgb_classification_report)


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011208 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1278
[LightGBM] [Info] Number of data points in the train set: 216570, number of used features: 6
[LightGBM] [Info] Start training from score -3.077331
[LightGBM] [Info] Start training from score -5.794946
[LightGBM] [Info] Start training from score -0.050373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No 

In [24]:
# #tune hyperparameters for lightgbm
# from sklearn.model_selection import GridSearchCV

# # scale the data
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_test_scaled = scaler.transform(X_test)

# le = LabelEncoder()
# y_trainLE = le.fit_transform(y_train)

# lgb_reg=lgb.LGBMClassifier()

# # define the grid of hyperparameters to search
# search_space = {'n_estimators': [100, 200, 500],
#                 'learning_rate': [0.01, 0.05, 0.1],
#                 'max_depth': [3, 5, 7]}
# # define search
# grid_search = GridSearchCV(lgb_reg, search_space, cv=5, scoring="accuracy", n_jobs=-1)
# # execute search
# grid_result = grid_search.fit(X_train_scaled, y_trainLE)
# # summarize result




In [26]:
# print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

### Create Ensemble model

In [27]:
from sklearn.ensemble import VotingClassifier

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)



ensemble_model = VotingClassifier(estimators=[
    ('Decision Tree', dt_class),
    ('CatBoost', cat_reg),
    ('XGBoost', xgb_class),
    ('LightGBM', lgb_reg)
], voting='soft')

ensemble_model.fit(X_train_scaled, y_train)
ensemble_predictions = ensemble_model.predict(X_test_scaled)

0:	learn: 0.3861038	total: 89.3ms	remaining: 44.5s
1:	learn: 0.2189519	total: 149ms	remaining: 37.1s
2:	learn: 0.1240743	total: 217ms	remaining: 36s
3:	learn: 0.0788224	total: 266ms	remaining: 33s
4:	learn: 0.0491858	total: 317ms	remaining: 31.4s
5:	learn: 0.0339245	total: 375ms	remaining: 30.9s
6:	learn: 0.0230531	total: 437ms	remaining: 30.8s
7:	learn: 0.0166981	total: 496ms	remaining: 30.5s
8:	learn: 0.0120986	total: 568ms	remaining: 31s
9:	learn: 0.0092694	total: 634ms	remaining: 31s
10:	learn: 0.0078769	total: 736ms	remaining: 32.7s
11:	learn: 0.0063803	total: 781ms	remaining: 31.8s
12:	learn: 0.0056869	total: 855ms	remaining: 32s
13:	learn: 0.0045628	total: 897ms	remaining: 31.2s
14:	learn: 0.0042310	total: 943ms	remaining: 30.5s
15:	learn: 0.0038234	total: 1.02s	remaining: 30.8s
16:	learn: 0.0033371	total: 1.09s	remaining: 31.1s
17:	learn: 0.0029969	total: 1.16s	remaining: 31s
18:	learn: 0.0028679	total: 1.22s	remaining: 30.8s
19:	learn: 0.0027808	total: 1.28s	remaining: 30.6s
2

In [32]:
# print accuracy score
ensemble_accuracy = accuracy_score(y_test, ensemble_predictions)
print("Accuracy: %.2f%%" % (ensemble_accuracy * 100.0))

Accuracy: 99.96%


#### create pickle

In [39]:
import pickle

model_name= 'dataset_7_ensemble_model.pkl'

# save
with open(model_name,'wb') as f:
    pickle.dump(ensemble_model,f)

# load
with open(model_name, 'rb') as f:
    ensemble_model_load = pickle.load(f)
    






In [34]:
# verify that the loaded model works
ensemble_model_load_predictions = ensemble_model_load.predict(X_test_scaled)
ensemble_model_load_accuracy = accuracy_score(y_test, ensemble_model_load_predictions)
print("Accuracy: %.2f%%" % (ensemble_model_load_accuracy * 100.0))

Accuracy: 99.96%


In [35]:
path=os.path.join(os.getcwd(),'data','7')
csv_files=glob.glob(path + "/*.csv")

csv_files_pickle=[csv_file for csv_file in csv_files if os.path.basename(csv_file).startswith('DRAWN')]

dataframes={}

for csv_file in csv_files_pickle:
  # print(csv_file)
  well_name=os.path.splitext(csv_file)[0]
  # print("file path")
  # print(os.path.join(csv_directory,csv_file))

  df = pd.read_csv(csv_file)
  # df_test = pd.read_csv(csv_file, nrows=100)

  # float_cols = [c for c in df_test if df_test[c].dtype == "float64"]
  # float32_cols = {c: np.float32 for c in float_cols}

  # df=pd.read_csv(csv_file, engine='c', dtype=float32_cols)
  dataframes[well_name]=df

for well_name,df in dataframes.items():
  df.insert(0,'name',well_name.split('_')[0].split('/')[-1])
  df.insert(1,'id',well_name.split('_')[1])

df=pd.concat(dataframes.values(),ignore_index=True)

distinct_wells=df['name'].unique()
for name in distinct_wells:
  print(name)

df

DRAWN


name     id                   timestamp     P-PDG      P-TPT  \
0        DRAWN  00009  2018-08-20 11:25:44.000000  235.0643   87.05141   
1        DRAWN  00009  2018-08-20 11:25:45.000000  235.0643   87.05141   
2        DRAWN  00009  2018-08-20 11:25:46.000000  235.0644   87.05141   
3        DRAWN  00009  2018-08-20 11:25:47.000000  235.0644   87.05141   
4        DRAWN  00009  2018-08-20 11:25:48.000000  235.0644   87.05141   
...        ...    ...                         ...       ...        ...   
2419205  DRAWN  00010  2018-08-21 11:25:40.000000  260.9383  211.88690   
2419206  DRAWN  00010  2018-08-21 11:25:41.000000  260.9383  211.88690   
2419207  DRAWN  00010  2018-08-21 11:25:42.000000  260.9383  211.88690   
2419208  DRAWN  00010  2018-08-21 11:25:43.000000  260.9383  211.88690   
2419209  DRAWN  00010  2018-08-21 11:25:44.000000  260.9383  211.88690   

            T-TPT  P-MON-CKP  T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  QGL  class  
0        109.9409   21.04113   59.85347         NaN         NaN  NaN      0  
1        109.9409   21.04113   59.85347         NaN         NaN  NaN      0  
2        109.9409   21.04113   59.85347         NaN         NaN  NaN      0  
3        109.9409   21.04113   59.85347         NaN         NaN  NaN      0  
4        109.9409   21.04113   59.85347         NaN         NaN  NaN      0  
...           ...        ...        ...         ...         ...  ...    ...  
2419205  117.8766  122.91520   65.02185         NaN         NaN  NaN      7  
2419206  117.8766  122.91520   65.02185         NaN         NaN  NaN      7  
2419207  117.8766  122.91520   65.02185         NaN         NaN  NaN      7  
2419208  117.8766  122.91520   65.02185         NaN         NaN  NaN      7  
2419209  117.8766  122.91520   65.02185         NaN         NaN  NaN      7  

[2419210 rows x 12 columns]

In [36]:
df.dropna()
#clean dataset to remove name, id, timestamp
df=df.drop(['name','id','timestamp','T-JUS-CKGL'],axis=1)

df=df.fillna(0)

df.replace([np.inf, -np.inf], 0, inplace=True)

In [37]:
y_sim = df["class"]


X = df.drop(['class'],axis=1)
y_pred = ensemble_model_load.predict(X)


accuracy = accuracy_score(y_sim, y_pred)
report = classification_report(y_sim, y_pred)

print(accuracy)
print(report)


/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/sklearn/base.py:458: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(
/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/xgboost/data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/xgboost/data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/xgboost/data.py:384: FutureWarning: is_catego

0.8448617523902431
              precision    recall  f1-score   support

           0       0.00      0.00      0.00    267503
           7       0.00      0.00      0.00    107809
         107       0.84      1.00      0.92   2043898

    accuracy                           0.84   2419210
   macro avg       0.28      0.33      0.31   2419210
weighted avg       0.71      0.84      0.77   2419210



/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Review

In [38]:
print()