# BC2406 Project

3 types:
* lin reg
* logistic reg
* CART (dec tree)

### Dataset 1

### Data Handling

In [38]:
import glob
import os
import pandas as pd

# csv_directory='/Users/cherylong/Desktop/1_aib_well_dataset'
# csv_files=[file for file in os.listdir(csv_directory) if file.endswith('.csv')]
# print(csv_files)
#import csv files
# print(csv_files)
path=os.path.join(os.getcwd(),'data','1')
csv_files=glob.glob(path + "/*.csv")

#remove BC2406.ipynb from csv_files
# csv_files.remove('BC2406.ipynb')

# remove all files whose file name (not path) starts with SIMULATED
# csv_files=[csv_file for csv_file in csv_files if not os.path.basename(csv_file).startswith('SIMULATED')]
csv_files=[csv_file for csv_file in csv_files if not os.path.basename(csv_file).startswith('DRAWN')]

dataframes={}
for csv_file in csv_files:
  well_name=os.path.splitext(csv_file)[0]
  df=pd.read_csv(csv_file)
  dataframes[well_name]=df

for well_name,df in dataframes.items():
  df.insert(0,'name',well_name.split('_')[0].split('/')[-1])
  df.insert(1,'id',well_name.split('_')[1])

df=pd.concat(dataframes.values(),ignore_index=True)

distinct_wells=df['name'].unique()
for name in distinct_wells:
  print(name)

# 

# float64_cols = list(df.select_dtypes(include="float64"))
# df[list(df.select_dtypes(include="float64"))] = df[list(df.select_dtypes(include="float64"))].astype("float32")

df


SIMULATED
WELL-00001
WELL-00002
WELL-00006


name     id                   timestamp       P-PDG       P-TPT  \
0        SIMULATED  00035  2018-10-06 11:30:10.000000  19895150.0  12202720.0   
1        SIMULATED  00035  2018-10-06 11:30:11.000000  19895150.0  12202720.0   
2        SIMULATED  00035  2018-10-06 11:30:12.000000  19895150.0  12202720.0   
3        SIMULATED  00035  2018-10-06 11:30:13.000000  19895150.0  12202720.0   
4        SIMULATED  00035  2018-10-06 11:30:14.000000  19895150.0  12202720.0   
...            ...    ...                         ...         ...         ...   
8441402  SIMULATED  00038  2018-10-07 12:28:36.000000  23708740.0  13660770.0   
8441403  SIMULATED  00038  2018-10-07 12:28:37.000000  23708740.0  13660770.0   
8441404  SIMULATED  00038  2018-10-07 12:28:38.000000  23708740.0  13660770.0   
8441405  SIMULATED  00038  2018-10-07 12:28:39.000000  23708740.0  13660770.0   
8441406  SIMULATED  00038  2018-10-07 12:28:40.000000  23708740.0  13660770.0   

            T-TPT  P-MON-CKP  T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  QGL  class  
0        94.10425  1153320.0   71.93039         NaN         NaN  NaN    0.0  
1        94.10425  1153320.0   71.93040         NaN         NaN  NaN    0.0  
2        94.10426  1153320.0   71.93042         NaN         NaN  NaN    0.0  
3        94.10426  1153320.0   71.93044         NaN         NaN  NaN    0.0  
4        94.10427  1153320.0   71.93045         NaN         NaN  NaN    0.0  
...           ...        ...        ...         ...         ...  ...    ...  
8441402  97.60462  1129454.0   83.24790         NaN         NaN  NaN    1.0  
8441403  97.60462  1115079.0   83.22288         NaN         NaN  NaN    1.0  
8441404  97.60462  1109266.0   83.21536         NaN         NaN  NaN    1.0  
8441405  97.60462  1129454.0   83.24790         NaN         NaN  NaN    1.0  
8441406  97.60462  1115079.0   83.22288         NaN         NaN  NaN    1.0  

[8441407 rows x 12 columns]

In [40]:
# show all values in column class
print(df['class'].unique())

# count number of 0, 101, 1

print("count of 0 in class label",len(df[df['class']==0]))
print("count of 1 in class label",len(df[df['class']==1]))
print("count of 101 in class label",len(df[df['class']==101]))

[  0. 101.   1.  nan]
count of 0 in class label 717591
count of 1 in class label 2878583
count of 101 in class label 4844214


In [41]:
# df.dropna()
#clean dataset to remove name, id, timestamp
df=df.drop(['name','id','timestamp'],axis=1)

df=df.fillna(0)

In [42]:
#split dataset into train and test
from sklearn.model_selection import train_test_split
X=df.drop(['class'],axis=1)
y=df['class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [43]:
print(X_train.dtypes)

P-PDG         float64
P-TPT         float64
T-TPT         float64
P-MON-CKP     float64
T-JUS-CKP     float64
P-JUS-CKGL    float64
T-JUS-CKGL    float64
QGL           float64
dtype: object


### Generate Models

### Linear Regression (Not good)

In [8]:
# from sklearn.model_selection import train_test_split
# import numpy as np

# train_set,test_set=train_test_split(df,test_size=0.2,random_state=42)
# #random state shuffles the data

# #train linear regression model on training set against class label
# from sklearn.linear_model import LinearRegression
# from sklearn.metrics import mean_squared_error
# from sklearn.metrics import mean_absolute_error
# from sklearn.metrics import r2_score

# #train model on training set
# lin_reg=LinearRegression()
# lin_reg.fit(train_set.drop('class',axis=1),train_set['class'])


# #predict class label on training set
# train_set_predictions=lin_reg.predict(train_set.drop('class',axis=1))
# lin_mse=mean_squared_error(train_set['class'],train_set_predictions)
# lin_rmse=np.sqrt(lin_mse)
# lin_mae=mean_absolute_error(train_set['class'],train_set_predictions)
# lin_r2=r2_score(train_set['class'],train_set_predictions)
# print("Training set RMSE: ",lin_rmse)
# print("Training set MAE: ",lin_mae)
# print("Training set R2: ",lin_r2)

# #predict class label on test set
# test_set_predictions=lin_reg.predict(test_set.drop('class',axis=1))
# lin_mse=mean_squared_error(test_set['class'],test_set_predictions)
# lin_rmse=np.sqrt(lin_mse)
# lin_mae=mean_absolute_error(test_set['class'],test_set_predictions)
# lin_r2=r2_score(test_set['class'],test_set_predictions)
# print("Test set RMSE: ",lin_rmse)
# print("Test set MAE: ",lin_mae)
# print("Test set R2: ",lin_r2)

### Logisitic Regression 

In [44]:
#train logistic regression model on training set against class label
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

#train model on training set
log_reg=LogisticRegression(max_iter=1000)
log_reg.fit(X_train,y_train)

#predict class label on training set
logreg_train_set_predictions=log_reg.predict(X_train)

#test model on test set
logreg_test_set_predictions=log_reg.predict(X_test)
log_accuracy=accuracy_score(y_test,logreg_test_set_predictions)
log_confusion_matrix=confusion_matrix(y_test,logreg_test_set_predictions)
log_classification_report=classification_report(y_test,logreg_test_set_predictions)

print("log_accuracy\n",log_accuracy)
print(log_confusion_matrix)
print(log_classification_report)
print("log_accuracy = %.1f"%(log_accuracy*100),"%")

/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/U

log_accuracy
 0.08561306701131682
[[144539      0      0]
 [575479      0      0]
 [968264      0      0]]
              precision    recall  f1-score   support

         0.0       0.09      1.00      0.16    144539
         1.0       0.00      0.00      0.00    575479
       101.0       0.00      0.00      0.00    968264

    accuracy                           0.09   1688282
   macro avg       0.03      0.33      0.05   1688282
weighted avg       0.01      0.09      0.01   1688282

log_accuracy = 8.6 %


/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Decision Tree (Not really sure what's going on here)

In [45]:
#train decision tree regression model on training set against class label
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import numpy as np

# convert everything to float32

X_train_32=X_train.astype('float32')
y_train_32=y_train.astype('float32')
X_test_32=X_test.astype('float32')
y_test_32=y_test.astype('float32')

# remove inf and nan
X_train_32=X_train_32.replace([np.inf, -np.inf], np.nan)
X_train_32=X_train_32.fillna(0)
y_train_32=y_train_32.replace([np.inf, -np.inf], np.nan)
y_train_32=y_train_32.fillna(0)
X_test_32=X_test_32.replace([np.inf, -np.inf], np.nan)
X_test_32=X_test_32.fillna(0)
y_test_32=y_test_32.replace([np.inf, -np.inf], np.nan)
y_test_32=y_test_32.fillna(0)

#train model on training set
dt_reg=DecisionTreeClassifier()
dt_reg.fit(X_train_32,y_train_32)

#predict class label on training set
dectree_train_set_predictions=dt_reg.predict(X_train_32)

#test model on test set
dectree_test_set_predictions=dt_reg.predict(X_test_32)
dt_mse=mean_squared_error(y_test_32,dectree_test_set_predictions)
dt_rmse=np.sqrt(dt_mse)
dt_accuracy=accuracy_score(y_test,dectree_test_set_predictions)
dt_confusion_matrix=confusion_matrix(y_test_32,dectree_test_set_predictions)

print("dt_mse\n",dt_mse)
print("dt_rmse\n",dt_rmse)
print("dt_accuracy\n",dt_accuracy)
print(dt_confusion_matrix)
print("dt_accuracy = %.1f"%(dt_accuracy*100),"%")


/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/pandas/core/dtypes/astype.py:134: RuntimeWarning: overflow encountered in cast
  return arr.astype(dtype, copy=True)
/Users/dyllon/Library/Mobile Documents/com~apple~CloudDocs/Uni/BC2406/.venv/lib/python3.11/site-packages/pandas/core/dtypes/astype.py:134: RuntimeWarning: overflow encountered in cast
  return arr.astype(dtype, copy=True)


dt_mse
 6.628874
dt_rmse
 2.5746598
dt_accuracy
 0.999336603719047
[[144538      0      1]
 [     1 574924    554]
 [     6    558 967700]]
dt_accuracy = 99.9 %


### XGBoost

In [ ]:
import xgboost as xgb
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()
y_trainLE = le.fit_transform(y_train)

In [ ]:
xgb_class=xgb.XGBClassifier()
xgb_class.fit(X_train,y_trainLE)

#predict class label on training set
xgb_train_set_predictions=xgb_class.predict(X_train)

#test model on test set
y_pred=xgb_class.predict(X_test)

In [ ]:
#train logistic regression model on training set against class label
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

#convert y_pred to 0,1,101
y_pred=np.round(y_pred)
y_pred=le.inverse_transform(y_pred.astype(int))

xgb_accuracy=accuracy_score(y_test,y_pred)
xgb_confusion_matrix=confusion_matrix(y_test,y_pred)
xgb_classification_report=classification_report(y_test,y_pred)

print("xgb_accuracy\n",xgb_accuracy)
print(xgb_confusion_matrix)
print(xgb_classification_report)


### CatBoost

In [ ]:
from catboost import CatBoostClassifier

In [ ]:

cat_reg=CatBoostClassifier()
cat_reg.fit(X_train,y_trainLE)

#predict class label on training set
cat_train_set_predictions=cat_reg.predict(X_train)

#test model on test set
cat_test_set_predictions=cat_reg.predict(X_test)


In [ ]:
#convert y_pred to 0,1,101
cat_test_set_predictions=np.round(cat_test_set_predictions)
cat_test_set_predictions=le.inverse_transform(cat_test_set_predictions.astype(int))

cat_accuracy=accuracy_score(y_test,cat_test_set_predictions)
cat_confusion_matrix=confusion_matrix(y_test,cat_test_set_predictions)

print("cat_accuracy\n",cat_accuracy)
print(cat_confusion_matrix)
print(xgb_classification_report)

### LightGBM  (Can't really download LightGBM)

In [ ]:

import lightgbm as lgb

In [ ]:
# #train lightgbm regression model on training set against class label


# le = LabelEncoder()
# y_trainLE = le.fit_transform(y_train)

lgb_reg=lgb.LGBMRegressor()
lgb_reg.fit(X_train,y_train)

#predict class label on training set
lgb_train_set_predictions=lgb_reg.predict(X_train)

#test model on test set
lgb_test_set_predictions=lgb_reg.predict(X_test)

In [ ]:
import numpy as np 
lgb_test_set_predictions=np.round(lgb_test_set_predictions)
lgb_test_set_predictions=le.inverse_transform(lgb_test_set_predictions.astype(int))

lgb_accuracy=accuracy_score(y_test,lgb_test_set_predictions)
lgb_confusion_matrix=confusion_matrix(y_test,lgb_test_set_predictions)
lgb_classification_report=classification_report(y_test,lgb_test_set_predictions)

print("lgb_accuracy\n",lgb_accuracy)
print(lgb_confusion_matrix)
print(xgb_classification_report)

### Compare Models

In [ ]:
# compare both models with f1 score
from sklearn.metrics import f1_score

# calculate F1 scores for both models
logreg_f1 = f1_score(y_test, logreg_test_set_predictions, average='weighted')
dectree_f1 = f1_score(y_test, dectree_test_set_predictions, average='weighted')

# print
print("F1 scores:")
print("Logistic Regression: ", logreg_f1)
print("Decision Tree Regressor: ", dectree_f1)

# compare F1 scores
if logreg_f1 > dectree_f1:
    print("Logistic Regression has a higher F1 score.")
elif logreg_f1 < dectree_f1:
    print("Decision Tree has a higher F1 score.")
else:
    print("Both models have the same F1 score.")


### Dataset 8


### Data Handling

In [ ]:

import os
import pandas as pd

csv_directory='/Users/cherylong/Desktop/8_hpl_well_dataset'
csv_files=[file for file in os.listdir(csv_directory) if file.endswith('.csv')]
print(csv_files)
dataframes={}
#import csv files
# print(csv_files)
# path=os.path.join(os.getcwd(),'data','3')
# csv_files=glob.glob(path + "/*.csv")

#remove BC2406.ipynb from csv_files
# csv_files.remove('BC2406.ipynb')

# remove all files whose file name (not path) starts with SIMULATED
#csv_files=[csv_file for csv_file in csv_files if not os.path.basename(csv_file).startswith('SIMULATED')]


for csv_file in csv_files:
  well_name=os.path.splitext(csv_file)[0]
  df=pd.read_csv(os.path.join(csv_directory,csv_file))
  dataframes[well_name]=df

for well_name,df in dataframes.items():
  df.insert(0,'name',well_name.split('_')[0])
  df.insert(1,'id',well_name.split('_')[1])

df=pd.concat(dataframes.values(),ignore_index=True)

distinct_wells=df['name'].unique()
for name in distinct_wells:
  print(name)

df

In [ ]:

#clean dataset to remove name, id, timestamp
df=df.drop(['name','id','timestamp', 'T-JUS-CKGL','P-JUS-CKGL','QGL'],axis=1)

#replace all NaN with 0
# df=df.fillna(0)

# drop all rows with class NaN
df=df.dropna(subset=['class'])

# # print NaN in any column

# drop all rows where P-PDG is NaN
df=df.dropna(subset=['P-PDG'])

print(df[df.isna().any(axis=1)])


In [ ]:
# show all values in column class
print(df['class'].unique())

# print 5 rows where class = NaN
print(df[df['class'].isna()].head())

#count number of 0, 3 in class label
print("count of 0 in class label: ",len(df[df['class']==0])) # normal state
print("count of NaN in class label: ",len(df[df['class'].isna()])) # NaN state
print("count of 8 in class label: ",len(df[df['class']==8]))  # warning state
print("count of 108 in class label: ",len(df[df['class']==108]))  # error state


In [ ]:
#split dataset into train and test
from sklearn.model_selection import train_test_split
X=df.drop(['class'],axis=1)
y=df['class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

### Generate Models

### Linear Regression

In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np

train_set,test_set=train_test_split(df,test_size=0.2,random_state=42)
#random state shuffles the data

#train linear regression model on training set against class label
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

#train model on training set
lin_reg=LinearRegression()
lin_reg.fit(train_set.drop('class',axis=1),train_set['class'])


#predict class label on training set
train_set_predictions=lin_reg.predict(train_set.drop('class',axis=1))
lin_mse=mean_squared_error(train_set['class'],train_set_predictions)
lin_rmse=np.sqrt(lin_mse)
lin_mae=mean_absolute_error(train_set['class'],train_set_predictions)
lin_r2=r2_score(train_set['class'],train_set_predictions)
print("Training set RMSE: ",lin_rmse)
print("Training set MAE: ",lin_mae)
print("Training set R2: ",lin_r2)

#predict class label on test set
test_set_predictions=lin_reg.predict(test_set.drop('class',axis=1))
lin_mse=mean_squared_error(test_set['class'],test_set_predictions)
lin_rmse=np.sqrt(lin_mse)
lin_mae=mean_absolute_error(test_set['class'],test_set_predictions)
lin_r2=r2_score(test_set['class'],test_set_predictions)
print("Test set RMSE: ",lin_rmse)
print("Test set MAE: ",lin_mae)
print("Test set R2: ",lin_r2)

#### Logistic Regression

In [ ]:
#train logistic regression model on training set against class label
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler

# scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#train model on training set
log_reg=LogisticRegression(max_iter=100000)
log_reg.fit(X_train_scaled,y_train)

#predict class label on training set
logreg_train_set_predictions=log_reg.predict(X_train_scaled)

#test model on test set
logreg_test_set_predictions=log_reg.predict(X_test_scaled)
log_accuracy=accuracy_score(y_test,logreg_test_set_predictions)
log_confusion_matrix=confusion_matrix(y_test,logreg_test_set_predictions)
log_classification_report=classification_report(y_test,logreg_test_set_predictions)


In [ ]:
print("log_accuracy\n",log_accuracy)
print(log_confusion_matrix)
print(log_classification_report)
print("log_accuracy = %.1f"%(log_accuracy*100),"%")

#### Decision Tree (not sure if this works)

In [ ]:
#train decision tree regression model on training set against class label
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

X_train = np.nan_to_num(X_train.astype(np.float64))
X_test = np.nan_to_num(X_test.astype(np.float64))

# check for infinite or NaN values in X_train and X_test
if not np.isfinite(X_train).all() or not np.isfinite(X_test).all():
    print("Input data contains infinite or NaN values.")

#train model on training set
dt_reg=DecisionTreeRegressor()
dt_reg.fit(X_train,y_train)

#predict class label on training set
dectree_train_set_predictions=dt_reg.predict(X_train)

#test model on test set
dectree_test_set_predictions=dt_reg.predict(X_test)
dt_mse=mean_squared_error(y_test,dectree_test_set_predictions)
dt_rmse=np.sqrt(dt_mse)
dt_accuracy=accuracy_score(y_test,dectree_test_set_predictions)
dt_confusion_matrix=confusion_matrix(y_test,dectree_test_set_predictions)

In [ ]:
print("dt_mse\n",dt_mse)
print("dt_rmse\n",dt_rmse)
print("dt_accuracy\n",dt_accuracy)
print(dt_confusion_matrix)
print("dt_accuracy = %.1f"%(dt_accuracy*100),"%")


### XGBoost

In [ ]:
#train xgboost regression model on training set against class label
import xgboost as xgb
import numpy as np
from sklearn.preprocessing import LabelEncoder

# scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

le = LabelEncoder()
y_trainLE = le.fit_transform(y_train)

xgb_class=xgb.XGBClassifier()
xgb_class.fit(X_train_scaled,y_trainLE)

#predict class label on training set
xgb_train_set_predictions=xgb_class.predict(X_train_scaled)

#test model on test set
y_pred=xgb_class.predict(X_test_scaled)

#convert y_pred
y_pred=np.round(y_pred)
y_pred=le.inverse_transform(y_pred.astype(int))

xgb_accuracy=accuracy_score(y_test,y_pred)
xgb_confusion_matrix=confusion_matrix(y_test,y_pred)
xgb_classification_report=classification_report(y_test,y_pred)

print("xgb_accuracy\n",xgb_accuracy)
print(xgb_confusion_matrix)
print(xgb_classification_report)

### catboost

In [ ]:
#train catboost regression model on training set against class label

# scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

le = LabelEncoder()
y_trainLE = le.fit_transform(y_train)

cat_reg=CatBoostClassifier()
cat_reg.fit(X_train_scaled,y_trainLE)

#predict class label on training set
cat_train_set_predictions=cat_reg.predict(X_train_scaled)


#test model on test set
cat_test_set_predictions=cat_reg.predict(X_test_scaled)

#convert y_pred
cat_test_set_predictions=np.round(cat_test_set_predictions)
cat_test_set_predictions=le.inverse_transform(cat_test_set_predictions.astype(int))

cat_accuracy=accuracy_score(y_test,cat_test_set_predictions)
cat_confusion_matrix=confusion_matrix(y_test,cat_test_set_predictions)
cat_classification_report=classification_report(y_test,cat_test_set_predictions)


In [ ]:
print("cat_accuracy\n",cat_accuracy)
print(cat_confusion_matrix)
print(cat_classification_report)

In [ ]:
#tune hyperparameters for catboost
from sklearn.model_selection import GridSearchCV

# scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

le = LabelEncoder()
y_trainLE = le.fit_transform(y_train)

cat_reg=CatBoostClassifier()

# define the grid of hyperparameters to search
search_space = {'iterations': [100, 200, 500],
                'learning_rate': [0.01, 0.05, 0.1],
                'depth': [3, 5, 7]}
# define search
grid_search = GridSearchCV(cat_reg, search_space, cv=5, scoring="accuracy", n_jobs=-1)
# execute search
grid_result = grid_search.fit(X_train_scaled, y_trainLE)
# summarize result
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

### LightGBM (can't install)

In [ ]:
import lightgbm as lgb
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

scaler = StandardScaler()

# scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#train lightgbm regression model on training set against class label
le = LabelEncoder()
y_trainLE = le.fit_transform(y_train)

lgb_reg=lgb.LGBMClassifier()
lgb_reg.fit(X_train_scaled,y_trainLE)

#predict class label on training set
lgb_train_set_predictions=lgb_reg.predict(X_train_scaled)

#test model on test set
lgb_test_set_predictions=lgb_reg.predict(X_test_scaled)

#convert y_pred
lgb_test_set_predictions=np.round(lgb_test_set_predictions)
lgb_test_set_predictions=le.inverse_transform(lgb_test_set_predictions.astype(int))

lgb_accuracy=accuracy_score(y_test,lgb_test_set_predictions)
lgb_confusion_matrix=confusion_matrix(y_test,lgb_test_set_predictions)
lgb_classification_report=classification_report(y_test,lgb_test_set_predictions)

print("lgb_accuracy\n",lgb_accuracy)
print(lgb_confusion_matrix)
print(lgb_classification_report)


In [ ]:
#tune hyperparameters for lightgbm
from sklearn.model_selection import GridSearchCV

# scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

le = LabelEncoder()
y_trainLE = le.fit_transform(y_train)

lgb_reg=lgb.LGBMClassifier()

# define the grid of hyperparameters to search
search_space = {'n_estimators': [100, 200, 500],
                'learning_rate': [0.01, 0.05, 0.1],
                'max_depth': [3, 5, 7]}
# define search
grid_search = GridSearchCV(lgb_reg, search_space, cv=5, scoring="accuracy", n_jobs=-1)
# execute search
grid_result = grid_search.fit(X_train_scaled, y_trainLE)
# summarize result


In [ ]:
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))